// External type stubs (opaque — not user-facing)
type CrossSection = unknown;
type Manifold = unknown;

// Generated by dts-bundle-generator v9.5.1

type Vec3 = [
	number,
	number,
	number
];
type Mat4 = [
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number
];
type TransformInput = Transform | Mat4;
type RotateAroundToMode = "plane" | "line";
interface RotateAroundToOptions {
	mode?: RotateAroundToMode;
}
declare class Transform {
	private readonly m;
	private constructor();
	static identity(): Transform;
	static from(input: TransformInput): Transform;
	static translation(x: number, y: number, z: number): Transform;
	static scale(v: number | Vec3): Transform;
	static rotationAxis(axis: Vec3, angleDeg: number, pivot?: Vec3): Transform;
	static rotateAroundTo(axis: Vec3, pivot: Vec3, movingPoint: Vec3, targetPoint: Vec3, options?: RotateAroundToOptions): Transform;
	/**
	 * Compose transforms in chain order.
	 * `a.mul(b)` means apply `a`, then `b`.
	 */
	mul(other: TransformInput): Transform;
	translate(x: number, y: number, z: number): Transform;
	rotateAxis(axis: Vec3, angleDeg: number, pivot?: Vec3): Transform;
	scale(v: number | Vec3): Transform;
	inverse(): Transform;
	point(p: Vec3): Vec3;
	vector(v: Vec3): Vec3;
	toArray(): Mat4;
}
/**
 * Compose transforms in chain order.
 * Equivalent to Transform.identity().mul(a).mul(b).mul(c)...
 */
declare function composeChain(...steps: TransformInput[]): Transform;
type SketchFace3D = "front" | "back" | "left" | "right" | "top" | "bottom";
interface ShapeQueryOwner {
	id: string;
	operation: string;
}
type TopologyRewriteQueryOutcome = "preserved" | "split" | "merged";
interface CanonicalFaceQueryRef {
	kind: "canonical-face";
	face: SketchFace3D;
	owner?: ShapeQueryOwner;
}
interface TrackedFaceQueryRef {
	kind: "tracked-face";
	faceName: string;
	owner?: ShapeQueryOwner;
}
interface DirectFaceQueryRef {
	kind: "face-ref";
	faceName?: string;
	owner?: ShapeQueryOwner;
}
interface PropagatedFaceQueryRef {
	kind: "propagated-face";
	rewriteId: string;
	outcome: TopologyRewriteQueryOutcome;
	source: FaceQueryRef;
	owner?: ShapeQueryOwner;
}
interface CreatedFaceQueryRef {
	kind: "created-face";
	rewriteId: string;
	operation: string;
	slot: string;
	owner?: ShapeQueryOwner;
}
type FaceQueryRef = CanonicalFaceQueryRef | TrackedFaceQueryRef | DirectFaceQueryRef | PropagatedFaceQueryRef | CreatedFaceQueryRef;
type EdgeQuerySelector = "edge" | "start" | "end" | "midpoint";
interface TrackedEdgeQueryRef {
	kind: "tracked-edge";
	edgeName: string;
	selector: EdgeQuerySelector;
	owner?: ShapeQueryOwner;
}
interface DirectEdgeQueryRef {
	kind: "edge-ref";
	edgeName?: string;
	selector: EdgeQuerySelector;
	owner?: ShapeQueryOwner;
}
interface PropagatedEdgeQueryRef {
	kind: "propagated-edge";
	rewriteId: string;
	outcome: TopologyRewriteQueryOutcome;
	source: EdgeQueryRef;
	selector: EdgeQuerySelector;
	owner?: ShapeQueryOwner;
}
interface CreatedEdgeQueryRef {
	kind: "created-edge";
	rewriteId: string;
	operation: string;
	slot: string;
	selector: EdgeQuerySelector;
	owner?: ShapeQueryOwner;
}
type EdgeQueryRef = TrackedEdgeQueryRef | DirectEdgeQueryRef | PropagatedEdgeQueryRef | CreatedEdgeQueryRef;
type Anchor = "center" | "top-left" | "top-right" | "bottom-left" | "bottom-right" | "top" | "bottom" | "left" | "right";
type SketchOperandInput = Sketch | readonly Sketch[];
declare class Sketch {
	readonly cross: CrossSection;
	colorHex: string | undefined;
	constructor(cross: CrossSection, color?: string);
	/** Set the color of this sketch (hex string, e.g. "#ff0000") */
	color(value: string | undefined): Sketch;
	/** Return a new Sketch wrapper for explicit duplication in scripts. */
	clone(): Sketch;
	/** Alias for clone() */
	duplicate(): Sketch;
	area(): number;
	bounds(): unknown;
	isEmpty(): boolean;
	numVert(): number;
	toPolygons(): unknown[];
	translate(x: number, y?: number): Sketch;
	rotate(degrees: number): Sketch;
	rotateAround(degrees: number, pivot: [
		number,
		number
	]): Sketch;
	scale(v: number | [
		number,
		number
	]): Sketch;
	mirror(ax: [
		number,
		number
	]): Sketch;
	add(...others: SketchOperandInput[]): Sketch;
	subtract(...others: SketchOperandInput[]): Sketch;
	intersect(...others: SketchOperandInput[]): Sketch;
	offset(delta: number, join?: "Square" | "Round" | "Miter"): Sketch;
	hull(): Sketch;
	simplify(epsilon?: number): Sketch;
	warp(fn: (vert: [
		number,
		number
	]) => void): Sketch;
	/**
	 * Decompose this sketch into its distinct filled regions. See `sketchRegions()`.
	 * Regions are returned largest-first by area.
	 */
	regions(): Sketch[];
	/**
	 * Select the single filled region that contains the given 2D seed point.
	 * Throws if the seed is outside all regions. See `sketchRegion()`.
	 */
	region(seed: [
		number,
		number
	]): Sketch;
	extrude(height: number, opts?: {
		twist?: number;
		divisions?: number;
		scaleTop?: number | [
			number,
			number
		];
		center?: boolean;
	}): Shape | any;
	revolve(degrees?: number, segments?: number): Shape;
	attachTo(target: Sketch, targetAnchor: Anchor, selfAnchor?: Anchor, offset?: [
		number,
		number
	]): Sketch;
	onFace(parentOrFace: Shape | {
		toShape(): Shape;
	} | {
		_bbox(): {
			min: number[];
			max: number[];
		};
	} | FaceRef, faceOrOpts?: "front" | "back" | "left" | "right" | "top" | "bottom" | string | FaceRef | {
		u?: number;
		v?: number;
		protrude?: number;
		selfAnchor?: Anchor;
	}, opts?: {
		u?: number;
		v?: number;
		protrude?: number;
		selfAnchor?: Anchor;
	}): Sketch;
}
interface ConstraintTypeMap {
	coincident: {
		a: PointId;
		b: PointId;
	};
}
interface ConstraintTypeMap {
	horizontal: {
		line: LineId;
	};
}
interface ConstraintTypeMap {
	vertical: {
		line: LineId;
	};
}
interface ConstraintTypeMap {
	parallel: {
		a: LineId;
		b: LineId;
	};
}
interface ConstraintTypeMap {
	perpendicular: {
		a: LineId;
		b: LineId;
	};
}
interface ConstraintTypeMap {
	tangent: {
		line?: LineId;
		circle?: CircleId;
		a?: CircleId;
		b?: CircleId;
	};
}
interface ConstraintTypeMap {
	equal: {
		a: LineId;
		b: LineId;
	};
}
interface ConstraintTypeMap {
	symmetric: {
		a: PointId;
		b: PointId;
		axis: LineId;
	};
}
interface ConstraintTypeMap {
	concentric: {
		a: CircleId;
		b: CircleId;
	};
}
interface ConstraintTypeMap {
	collinear: {
		point: PointId;
		line: LineId;
	};
}
interface ConstraintTypeMap {
	fixed: {
		point: PointId;
		x: number;
		y: number;
	};
}
interface ConstraintTypeMap {
	midpoint: {
		point: PointId;
		line: LineId;
	};
}
interface ConstraintTypeMap {
	pointOnCircle: {
		point: PointId;
		circle: CircleId;
	};
}
interface ConstraintTypeMap {
	distance: {
		a: PointId;
		b: PointId;
		value: number;
	};
}
interface ConstraintTypeMap {
	length: {
		line: LineId;
		value: number;
	};
}
interface ConstraintTypeMap {
	angle: {
		a: LineId;
		b: LineId;
		value: number;
	};
}
interface ConstraintTypeMap {
	radius: {
		circle: CircleId;
		value: number;
	};
}
interface ConstraintTypeMap {
	diameter: {
		circle: CircleId;
		value: number;
	};
}
interface ConstraintTypeMap {
	hDistance: {
		a: PointId;
		b: PointId;
		value: number;
	};
}
interface ConstraintTypeMap {
	vDistance: {
		a: PointId;
		b: PointId;
		value: number;
	};
}
type PointId = string;
type LineId = string;
type CircleId = string;
interface SketchPoint {
	id: PointId;
	x: number;
	y: number;
	fixed: boolean;
}
interface SketchLine {
	id: LineId;
	a: PointId;
	b: PointId;
	construction: boolean;
}
interface SketchCircle {
	id: CircleId;
	center: PointId;
	radius: number;
	construction: boolean;
	fixedRadius: boolean;
	segments: number;
}
type SketchLoop = {
	type: "poly";
	points: PointId[];
} | {
	type: "circle";
	circle: CircleId;
};
interface ConstraintDisplay {
	id: string;
	type: string;
	label: string;
	position: [
		number,
		number
	];
	value?: number;
	isDimension: boolean;
	isConflicting: boolean;
}
interface SketchConstraintMeta {
	status: "under" | "fully" | "over";
	maxError: number;
	constraints: ConstraintDisplay[];
	rejected: ConstraintDisplay[];
	construction: {
		lines: {
			a: [
				number,
				number
			];
			b: [
				number,
				number
			];
		}[];
		circles: {
			center: [
				number,
				number
			];
			radius: number;
		}[];
	};
	/** Non-construction geometry edges rendered as solid wireframe overlay. */
	edges: {
		lines: {
			a: [
				number,
				number
			];
			b: [
				number,
				number
			];
		}[];
		circles: {
			center: [
				number,
				number
			];
			radius: number;
		}[];
		points: {
			id: string;
			pos: [number, number];
		}[];
	};
}
interface ConstraintDefinition {
	points: SketchPoint[];
	lines: SketchLine[];
	circles: SketchCircle[];
	loops: SketchLoop[];
	constraints: SketchConstraint[];
	rejectedConstraints: SketchConstraint[];
}
interface SolveOptions {
	iterations?: number;
	tolerance?: number;
}
interface ConstraintTypeMap {
}
interface ConstraintBuilderMethods {
}
type SketchConstraint = {
	[K in keyof ConstraintTypeMap]: {
		id: string;
		type: K;
	} & ConstraintTypeMap[K];
}[keyof ConstraintTypeMap];
interface ConstraintTypeMap {
	lineDistance: {
		a: LineId;
		b: LineId;
		value: number;
	};
}
/** Exported for backward-compatibility with forge-public-api.ts */
type LineDistanceConstraint = {
	id: string;
	type: "lineDistance";
} & {
	a: LineId;
	b: LineId;
	value: number;
};
declare class ConstraintSketch extends Sketch {
	readonly constraintMeta: SketchConstraintMeta;
	readonly definition: ConstraintDefinition;
	constructor(cross: Sketch["cross"], constraintMeta: SketchConstraintMeta, definition: ConstraintDefinition);
	/**
	 * Enumerate all bounded regions formed by the line arrangement of this sketch.
	 * Construction lines are excluded. Regions are returned largest-first by area.
	 */
	detectArrangement(): Sketch[];
	/**
	 * Select the single arrangement region that contains the given seed point.
	 * Throws if no region contains the seed.
	 */
	detectArrangementRegion(seed: [
		number,
		number
	]): Sketch;
	withUpdatedConstraint(constraintId: string, value: number): ConstraintSketch;
	/**
	 * Return a human-readable diagnostic string of the solved state.
	 */
	inspect(): string;
}
interface ConstrainedSketchOptions {
	/** When true, adding a constraint that cannot be satisfied throws instead of silently discarding it. */
	strict?: boolean;
}
interface ConstrainedSketchBuilder extends ConstraintBuilderMethods {
}
declare class ConstrainedSketchBuilder {
	private points;
	private lines;
	private circles;
	private constraints;
	private loops;
	private rejectedConstraints;
	private cursor;
	private loopStart;
	private nextId;
	private strict;
	constructor(options?: ConstrainedSketchOptions);
	point(x: number, y: number, fixed?: boolean): PointId;
	pointAt(index: number): PointId;
	line(a: PointId, b: PointId, construction?: boolean): LineId;
	lineAt(index: number): LineId;
	circle(center: PointId, radius: number, construction?: boolean, segments?: number): CircleId;
	circleAt(index: number): CircleId;
	moveTo(x: number, y: number): this;
	lineTo(x: number, y: number): this;
	lineH(dx: number): this;
	lineV(dy: number): this;
	lineAngled(length: number, degrees: number): this;
	close(): this;
	addLoopCircle(center: PointId, radius: number, segments?: number): this;
	constrain(constraint: Omit<SketchConstraint, "id">): this;
	/** Constrain a line to be horizontal. */
	horizontal(line: LineId): this;
	/** Constrain a line to be vertical. */
	vertical(line: LineId): this;
	/** Constrain two lines to be parallel. */
	parallel(a: LineId, b: LineId): this;
	/** Constrain two lines to be perpendicular. */
	perpendicular(a: LineId, b: LineId): this;
	/**
	 * Tangent constraint.
	 * - `tangent(line, circle)` — line is tangent to a circle.
	 * - `tangent(circleA, circleB)` — two circles are externally tangent.
	 */
	tangent(a: LineId | CircleId, b: CircleId): this;
	/** Constrain two lines to have equal length. */
	equal(a: LineId, b: LineId): this;
	/** Constrain two points to be at the same location. */
	coincident(a: PointId, b: PointId): this;
	/** Constrain two circles to share the same center. */
	concentric(a: CircleId, b: CircleId): this;
	/** Constrain a point to lie on an infinite line (collinear). */
	collinear(point: PointId, line: LineId): this;
	/** Constrain two points to be symmetric about an axis line. */
	symmetric(a: PointId, b: PointId, axis: LineId): this;
	/** Fix a point at a specific location (or at its current position if x/y are omitted). */
	fix(point: PointId, x?: number, y?: number): this;
	/** Constrain a point to lie at the midpoint of a line. */
	midpoint(point: PointId, line: LineId): this;
	/** Constrain a point to lie on the perimeter of a circle. */
	pointOnCircle(point: PointId, circle: CircleId): this;
	/** Constrain the distance between two points. */
	distance(a: PointId, b: PointId, value: number): this;
	/** Constrain the length of a line. */
	length(line: LineId, value: number): this;
	/** Constrain the angle from line `a` to line `b` (degrees). */
	angle(a: LineId, b: LineId, value: number): this;
	/** Constrain the radius of a circle. */
	radius(circle: CircleId, value: number): this;
	/** Constrain the diameter of a circle. */
	diameter(circle: CircleId, value: number): this;
	/** Constrain the horizontal distance between two points (b.x − a.x = value). */
	hDistance(a: PointId, b: PointId, value: number): this;
	/** Constrain the vertical distance between two points (b.y − a.y = value). */
	vDistance(a: PointId, b: PointId, value: number): this;
	/**
	 * Constrain the perpendicular (offset) distance between two lines.
	 * Also implicitly enforces parallelism.
	 *
	 * Positive `value` places line `b` on the **left** side of line `a`
	 * (according to `a`'s direction vector). Negative places it on the right.
	 */
	lineDistance(a: LineId, b: LineId, value: number): this;
	/**
	 * Register a closed polygon loop from an explicit ordered list of point IDs.
	 */
	addLoop(points: PointId[]): this;
	solve(options?: SolveOptions): ConstraintSketch;
	buildDefinition(extraConstraint?: SketchConstraint): ConstraintDefinition;
	private getPoint;
	/** Import a Point2D, returning its PointId */
	importPoint(pt: {
		x: number;
		y: number;
	}, fixed?: boolean): PointId;
	/** Import a Line2D (two points + line), returning its LineId */
	importLine(l: {
		start: {
			x: number;
			y: number;
		};
		end: {
			x: number;
			y: number;
		};
	}, fixed?: boolean): LineId;
	/** Import a Rectangle2D as 4 points + 4 lines, returning side LineIds keyed by name */
	importRectangle(r: {
		vertices: [
			{
				x: number;
				y: number;
			},
			{
				x: number;
				y: number;
			},
			{
				x: number;
				y: number;
			},
			{
				x: number;
				y: number;
			}
		];
	}, fixed?: boolean): {
		bottom: LineId;
		right: LineId;
		top: LineId;
		left: LineId;
		points: [
			PointId,
			PointId,
			PointId,
			PointId
		];
	};
	/**
	 * Add a fixed reference point at (x, y).
	 */
	referencePoint(x: number, y: number): PointId;
	/**
	 * Add a fixed reference line from (x1, y1) to (x2, y2).
	 */
	referenceLine(x1: number, y1: number, x2: number, y2: number): LineId;
	/**
	 * Import a single named entity (point or line) from a solved `ConstraintSketch`
	 * as fixed reference geometry in this builder.
	 */
	referenceFrom(source: ConstraintSketch, entityId: string): PointId | LineId | null;
	/**
	 * Import ALL non-construction entities from a solved `ConstraintSketch` as
	 * fixed reference geometry.
	 */
	referenceAllFrom(source: ConstraintSketch): {
		points: Map<string, PointId>;
		lines: Map<string, LineId>;
	};
}
declare function constrainedSketch(options?: ConstrainedSketchOptions): ConstrainedSketchBuilder;
declare class Point2D {
	readonly x: number;
	readonly y: number;
	constructor(x: number, y: number);
	distanceTo(other: Point2D): number;
	midpointTo(other: Point2D): Point2D;
	translate(dx: number, dy: number): Point2D;
	toTuple(): [
		number,
		number
	];
}
declare function point(x: number, y: number): Point2D;
declare class Line2D {
	readonly start: Point2D;
	readonly end: Point2D;
	constructor(start: Point2D, end: Point2D);
	get length(): number;
	get midpoint(): Point2D;
	get angle(): number;
	get direction(): [
		number,
		number
	];
	/** Create a line parallel to this one, offset by distance. positive = left of direction */
	parallel(distance: number): Line2D;
	/**
	 * Intersection point of two lines (treating them as infinite lines).
	 * Returns null if lines are parallel.
	 */
	intersect(other: Line2D): Point2D | null;
	/**
	 * Intersection point within both line segments only.
	 * Returns null if segments don't cross.
	 */
	intersectSegment(other: Line2D): Point2D | null;
	static fromCoordinates(x1: number, y1: number, x2: number, y2: number): Line2D;
	static fromPointAndAngle(origin: Point2D, angleDeg: number, length: number): Line2D;
	static fromPointAndDirection(origin: Point2D, dir: [
		number,
		number
	], length: number): Line2D;
}
declare function line(x1: number, y1: number, x2: number, y2: number): Line2D;
declare class Circle2D {
	readonly center: Point2D;
	readonly radius: number;
	constructor(center: Point2D, radius: number);
	get diameter(): number;
	get circumference(): number;
	get area(): number;
	/** Point on the circle at given angle (degrees, 0=right, CCW) */
	pointAtAngle(angleDeg: number): Point2D;
	translate(dx: number, dy: number): Circle2D;
	toSketch(segments?: number): Sketch;
	/** Extrude to TrackedShape with top/bottom/side faces */
	extrude(height: number, segments?: number): TrackedShape;
	static fromCenterAndRadius(center: Point2D, radius: number): Circle2D;
	static fromDiameter(center: Point2D, diameter: number): Circle2D;
}
declare function circle(cx: number, cy: number, radius: number): Circle2D;
type RectSide = "top" | "bottom" | "left" | "right";
type RectVertex = "top-left" | "top-right" | "bottom-left" | "bottom-right";
/**
 * A rectangle with named sides and vertices.
 * Sides are named based on the rectangle's local orientation at construction time.
 * Vertices go: bottom-left, bottom-right, top-right, top-left (CCW from bottom-left).
 */
declare class Rectangle2D {
	/** Vertices in order: bottom-left, bottom-right, top-right, top-left */
	readonly vertices: [
		Point2D,
		Point2D,
		Point2D,
		Point2D
	];
	constructor(vertices: [
		Point2D,
		Point2D,
		Point2D,
		Point2D
	]);
	get width(): number;
	get height(): number;
	get center(): Point2D;
	side(name: RectSide): Line2D;
	/** Get side by index (0=bottom, 1=right, 2=top, 3=left) */
	sideAt(index: number): Line2D;
	vertex(name: RectVertex): Point2D;
	/** Get the two diagonals of this rectangle */
	diagonals(): [
		Line2D,
		Line2D
	];
	toSketch(): Sketch;
	translate(dx: number, dy: number): Rectangle2D;
	/** Create from origin corner + width/height (axis-aligned) */
	static fromDimensions(x: number, y: number, width: number, height: number): Rectangle2D;
	/** Create centered at a point */
	static fromCenterAndDimensions(center: Point2D, width: number, height: number): Rectangle2D;
	/** Create from two opposite corners (axis-aligned) */
	static from2Corners(p1: Point2D, p2: Point2D): Rectangle2D;
	/** Create from three points (free angle). p1-p2 defines one side, p3 gives the height direction. */
	static from3Points(p1: Point2D, p2: Point2D, p3: Point2D): Rectangle2D;
	/** Extrude this rectangle into a 3D TrackedShape with named faces and edges */
	extrude(height: number, up?: boolean): TrackedShape;
}
declare function rectangle(x: number, y: number, width: number, height: number): Rectangle2D;
/** Convert degrees to degrees (identity — for readability in scripts) */
declare function degrees(deg: number): number;
/** Convert radians to degrees */
declare function radians(rad: number): number;
type LineArg = LineId | Line2D;
type PointArg = PointId | Point2D;
declare const Constraint: {
	makeParallel(builder: ConstrainedSketchBuilder, a: LineArg, b: LineArg): ConstrainedSketchBuilder;
	enforceAngle(builder: ConstrainedSketchBuilder, a: LineArg, b: LineArg, angleDeg: number): ConstrainedSketchBuilder;
	horizontal(builder: ConstrainedSketchBuilder, line: LineArg): ConstrainedSketchBuilder;
	vertical(builder: ConstrainedSketchBuilder, line: LineArg): ConstrainedSketchBuilder;
	equalLength(builder: ConstrainedSketchBuilder, a: LineArg, b: LineArg): ConstrainedSketchBuilder;
	distance(builder: ConstrainedSketchBuilder, a: PointArg, b: PointArg, value: number): ConstrainedSketchBuilder;
	fix(builder: ConstrainedSketchBuilder, pt: PointArg, x: number, y: number): ConstrainedSketchBuilder;
	coincident(builder: ConstrainedSketchBuilder, a: PointArg, b: PointArg): ConstrainedSketchBuilder;
	perpendicular(builder: ConstrainedSketchBuilder, a: LineArg, b: LineArg): ConstrainedSketchBuilder;
	length(builder: ConstrainedSketchBuilder, line: LineArg, value: number): ConstrainedSketchBuilder;
};
type FaceDescendantSemantic = "face" | "region" | "set";
interface FaceDescendantMetadata {
	kind: "single" | "face-set";
	semantic: FaceDescendantSemantic;
	memberCount: number;
	memberNames: string[];
	coplanar: boolean;
}
type FaceName = string;
type EdgeName = string;
interface FaceRef {
	name: FaceName;
	/** Normal direction of the face */
	normal: [
		number,
		number,
		number
	];
	/** Center point of the face */
	center: [
		number,
		number,
		number
	];
	/** Compiler-owned face query when available. */
	query?: FaceQueryRef;
	/** True when the face can host a 2D sketch placement frame */
	planar?: boolean;
	/** Face-local horizontal axis for planar faces */
	uAxis?: [
		number,
		number,
		number
	];
	/** Face-local vertical axis for planar faces */
	vAxis?: [
		number,
		number,
		number
	];
	/** Shared descendant-resolution metadata when this face is a semantic region/set. */
	descendant?: FaceDescendantMetadata;
}
interface EdgeRef {
	name: EdgeName;
	/** Start point */
	start: [
		number,
		number,
		number
	];
	/** End point */
	end: [
		number,
		number,
		number
	];
	/** Compiler-owned edge query when available. */
	query?: EdgeQueryRef;
}
interface Topology {
	faces: Map<FaceName, FaceRef>;
	edges: Map<EdgeName, EdgeRef>;
}
/**
 * A Shape that knows its topology — which faces and edges it has by name.
 * Created by extruding known geometry (rectangles, polygons with named edges).
 */
declare class TrackedShape {
	readonly shape: Shape;
	readonly topology: Topology;
	private readonly baseHeight;
	private readonly extrudeUp;
	constructor(shape: Shape, topology: Topology, baseHeight: number, extrudeUp: boolean);
	/** Get a named face */
	face(name: FaceName): FaceRef;
	/** Get a named edge */
	edge(name: EdgeName): EdgeRef;
	/** List all face names */
	faceNames(): FaceName[];
	/** List all edge names */
	edgeNames(): EdgeName[];
	/** Return a new TrackedShape wrapper with copied topology metadata. */
	clone(): TrackedShape;
	/** Alias for clone() */
	duplicate(): TrackedShape;
	/** Inspect backend/representation info, including tracked-topology status. */
	geometryInfo(): GeometryInfo;
	/** Attach named placement references that survive normal transforms and imports. */
	withReferences(refs: PlacementReferenceInput): TrackedShape;
	/** List named placement references carried by this tracked shape. */
	referenceNames(kind?: "points" | "edges" | "surfaces" | "objects"): string[];
	/** Resolve a named placement reference or built-in anchor to a 3D point. */
	referencePoint(ref: string): [
		number,
		number,
		number
	];
	/** Translate the tracked shape so the given reference lands on the target coordinate. */
	placeReference(ref: string, target: [
		number,
		number,
		number
	], offset?: [
		number,
		number,
		number
	]): TrackedShape;
	translate(x: number, y: number, z: number): TrackedShape;
	/** Move so bounding box min corner is at the given global coordinate */
	moveTo(x: number, y: number, z: number): TrackedShape;
	/** Move so bounding box min corner is at target's bounding box min + (x, y, z) offset */
	moveToLocal(target: Shape | TrackedShape, x: number, y: number, z: number): TrackedShape;
	/** Alias for translate — matches ideal API's moveBy */
	moveBy(x: number, y: number, z: number): TrackedShape;
	/** Rotate around a named edge by angle in degrees */
	rotateAroundEdge(edgeName: EdgeName, angleDeg: number): TrackedShape;
	/** Rotate using Euler angles (degrees), topology is cleared */
	rotate(x: number, y: number, z: number): TrackedShape;
	/** Apply a 4x4 transform matrix or Transform object. Topology is cleared. */
	transform(m: Mat4 | Transform): TrackedShape;
	/** Reorient so primary axis (Z) points along direction. Topology is cleared. */
	pointAlong(direction: [
		number,
		number,
		number
	]): TrackedShape;
	/** Rotate around an arbitrary axis through a pivot point. Topology is cleared. */
	rotateAround(axis: [
		number,
		number,
		number
	], angleDeg: number, pivot?: [
		number,
		number,
		number
	]): TrackedShape;
	/** Rotate around an axis until a moving point reaches the target line/plane defined by the axis and target point. */
	rotateAroundTo(axis: [
		number,
		number,
		number
	], pivot: [
		number,
		number,
		number
	], movingPoint: string | [
		number,
		number,
		number
	], targetPoint: string | [
		number,
		number,
		number
	], options?: RotateAroundToOptions): TrackedShape;
	/** Scale the shape. Topology is cleared for non-uniform scale. */
	scale(v: number | [
		number,
		number,
		number
	]): TrackedShape;
	/** Mirror across a plane. Topology is cleared. */
	mirror(normal: [
		number,
		number,
		number
	]): TrackedShape;
	/** Set the display color. Returns a new TrackedShape. */
	color(value: string | undefined): TrackedShape;
	/** Access the underlying Shape for boolean ops etc */
	toShape(): Shape;
	/** Position this tracked shape relative to another using named 3D anchor points */
	attachTo(target: Shape | TrackedShape | {
		_bbox(): {
			min: number[];
			max: number[];
		};
	}, targetAnchor: string, selfAnchor?: string, offset?: [
		number,
		number,
		number
	]): TrackedShape;
	/**
	 * Place this shape on a face of a parent shape.
	 * See Shape.onFace() for full documentation.
	 */
	onFace(parent: Shape | TrackedShape | {
		_bbox(): {
			min: number[];
			max: number[];
		};
	}, face: "front" | "back" | "left" | "right" | "top" | "bottom", opts?: {
		u?: number;
		v?: number;
		protrude?: number;
	}): TrackedShape;
	/** Boolean subtract — returns plain Shape (topology lost) */
	subtract(...others: ShapeOperandInput[]): Shape;
	/** Boolean add — returns plain Shape (topology lost) */
	add(...others: ShapeOperandInput[]): Shape;
	/** Boolean intersect — returns plain Shape (topology lost) */
	intersect(...others: ShapeOperandInput[]): Shape;
	/** Shelling returns a plain Shape because tracked topology is not preserved. */
	shell(thickness: number, opts?: {
		openFaces?: Array<"top" | "bottom">;
	}): Shape;
	boundingBox(): unknown;
	get volume(): number;
}
type PlaneSpec = {
	origin: Vec3;
	normal: Vec3;
} | {
	plane: "XY" | "XZ" | "YZ";
	offset?: number;
} | {
	face: FaceRef;
};
declare const SHEET_METAL_EDGES: readonly [
	"top",
	"right",
	"bottom",
	"left"
];
type SheetMetalEdge = (typeof SHEET_METAL_EDGES)[number];
type SheetMetalPlanarRegionName = "panel" | `flange-${SheetMetalEdge}`;
type SheetMetalRegionName = SheetMetalPlanarRegionName | `bend-${SheetMetalEdge}`;
interface SheetMetalBendAllowance {
	kind: "k-factor";
	kFactor: number;
}
interface SheetMetalPanelSpec {
	width: number;
	height: number;
}
interface SheetMetalFlangeSpec {
	edge: SheetMetalEdge;
	length: number;
	angleDeg: number;
}
interface SheetMetalCornerReliefSpec {
	kind: "rect";
	size: number;
}
interface SheetMetalModel {
	panel: SheetMetalPanelSpec;
	thickness: number;
	bendRadius: number;
	bendAllowance: SheetMetalBendAllowance;
	cornerRelief: SheetMetalCornerReliefSpec;
	flanges: SheetMetalFlangeSpec[];
}
declare const ANCHOR3D_NAMES: readonly [
	"center",
	"front",
	"back",
	"left",
	"right",
	"top",
	"bottom",
	"front-left",
	"front-right",
	"back-left",
	"back-right",
	"top-front",
	"top-back",
	"top-left",
	"top-right",
	"bottom-front",
	"bottom-back",
	"bottom-left",
	"bottom-right",
	"top-front-left",
	"top-front-right",
	"top-back-left",
	"top-back-right",
	"bottom-front-left",
	"bottom-front-right",
	"bottom-back-left",
	"bottom-back-right"
];
type Anchor3D = typeof ANCHOR3D_NAMES[number];
type PlacementReferenceKind = "points" | "edges" | "surfaces" | "objects";
interface PlacementEdgeRef {
	start: Vec3;
	end: Vec3;
}
interface PlacementSurfaceRef {
	center: Vec3;
	normal: Vec3;
}
interface PlacementObjectRef {
	min: Vec3;
	max: Vec3;
}
interface PlacementReferences {
	points: Record<string, Vec3>;
	edges: Record<string, PlacementEdgeRef>;
	surfaces: Record<string, PlacementSurfaceRef>;
	objects: Record<string, PlacementObjectRef>;
}
type PlacementObjectInput = PlacementObjectRef | {
	min: [
		number,
		number,
		number
	];
	max: [
		number,
		number,
		number
	];
} | {
	boundingBox(): {
		min: number[];
		max: number[];
	};
} | {
	_bbox(): {
		min: number[];
		max: number[];
	};
};
interface PlacementReferenceInput {
	points?: Record<string, [
		number,
		number,
		number
	]>;
	edges?: Record<string, PlacementEdgeRef>;
	surfaces?: Record<string, PlacementSurfaceRef>;
	objects?: Record<string, PlacementObjectInput>;
}
type PlacementAnchorLike = Anchor3D | string;
declare const SHAPE_BACKEND_MARKER: unique symbol;
type ShapeRuntimeBounds = ReturnType<Manifold["boundingBox"]>;
type ShapeRuntimeMesh = ReturnType<Manifold["getMesh"]>;
type ShapeRuntimeCrossSection = ReturnType<Manifold["slice"]>;
interface ShapeBackend {
	readonly [SHAPE_BACKEND_MARKER]: true;
	clone(): ShapeBackend;
	translate(x: number, y: number, z: number): ShapeBackend;
	rotate(x: number, y: number, z: number): ShapeBackend;
	transform(m: Mat4): ShapeBackend;
	scale(v: number | [
		number,
		number,
		number
	]): ShapeBackend;
	mirror(normal: [
		number,
		number,
		number
	]): ShapeBackend;
	smoothOut(minSharpAngle: number, minSmoothness: number): ShapeBackend;
	refine(steps: number): ShapeBackend;
	refineToLength(length: number): ShapeBackend;
	refineToTolerance(tolerance: number): ShapeBackend;
	warp(fn: (vert: [
		number,
		number,
		number
	]) => void): ShapeBackend;
	split(other: ShapeBackend): [
		ShapeBackend,
		ShapeBackend
	];
	splitByPlane(normal: [
		number,
		number,
		number
	], originOffset: number): [
		ShapeBackend,
		ShapeBackend
	];
	trimByPlane(normal: [
		number,
		number,
		number
	], originOffset: number): ShapeBackend;
	hull(): ShapeBackend;
	simplify(tolerance?: number): ShapeBackend;
	boundingBox(): ShapeRuntimeBounds;
	volume(): number;
	surfaceArea(): number;
	minGap(other: ShapeBackend, searchLength: number): number;
	isEmpty(): boolean;
	numTri(): number;
	getMesh(): ShapeRuntimeMesh;
	slice(offset: number): ShapeRuntimeCrossSection;
	project(): ShapeRuntimeCrossSection;
	requireManifold(apiName?: string): Manifold;
}
interface TransformationStep {
	kind: string;
	description: string;
	details?: Record<string, unknown>;
}
type TimelineEntryCategory = "primitive" | "sketch" | "modifier" | "boolean" | "transform";
interface TimelineEntry {
	kind: string;
	label: string;
	summary: string;
	category: TimelineEntryCategory;
}
interface FaceTransformationHistory {
	faceName: string;
	origin: {
		operation: string;
		owner?: ShapeQueryOwner;
	};
	transformations: TransformationStep[];
	query?: FaceQueryRef;
	/** Ordered list of operations that built this shape, oldest first. */
	timeline: TimelineEntry[];
}
declare function rect(width: number, height: number, center?: boolean): Sketch;
declare function circle2d(radius: number, segments?: number): Sketch;
declare function roundedRect(width: number, height: number, radius: number, center?: boolean): Sketch;
declare function polygon(points: ([
	number,
	number
] | Point2D)[]): Sketch;
declare function ngon(sides: number, radius: number): Sketch;
declare function ellipse(rx: number, ry: number, segments?: number): Sketch;
declare function slot(length: number, width: number): Sketch;
declare function star(points: number, outerR: number, innerR: number): Sketch;
type SketchFaceTarget = SketchFace3D | string | FaceRef;
declare function union2d(...inputs: SketchOperandInput[]): Sketch;
declare function difference2d(...inputs: SketchOperandInput[]): Sketch;
declare function intersection2d(...inputs: SketchOperandInput[]): Sketch;
declare function hull2d(...inputs: SketchOperandInput[]): Sketch;
declare class PathBuilder {
	private points;
	private x;
	private y;
	moveTo(x: number, y: number): this;
	lineTo(x: number, y: number): this;
	lineH(dx: number): this;
	lineV(dy: number): this;
	lineAngled(length: number, degrees: number): this;
	close(): Sketch;
	stroke(width: number, join?: "Round" | "Square"): Sketch;
}
declare function path(): PathBuilder;
declare function stroke(points: [
	number,
	number
][], width: number, join?: "Round" | "Square"): Sketch;
type ShapeArg = Shape | TrackedShape;
/** Repeat a shape along a direction vector */
declare function linearPattern(shape: ShapeArg, count: number, dx: number, dy: number, dz?: number): Shape;
/** Repeat a shape around the Z axis */
declare function circularPattern(shape: ShapeArg, count: number, centerX?: number, centerY?: number): Shape;
/** Mirror a shape and union with original */
declare function mirrorCopy(shape: ShapeArg, normal: [
	number,
	number,
	number
]): Shape;
type ShapeArg$1 = Shape | TrackedShape;
declare function filletEdge(shape: ShapeArg$1, edge: EdgeRef, radius: number, quadrant?: [
	number,
	number
], segments?: number): Shape;
declare function chamferEdge(shape: ShapeArg$1, edge: EdgeRef, size: number, quadrant?: [
	number,
	number
]): Shape;
interface FilletCornerSpec {
	index: number;
	radius: number;
	segments?: number;
}
type PointInput = [
	number,
	number
] | Point2D;
declare function filletCorners(points: PointInput[], corners: FilletCornerSpec[]): Sketch;
type Vec3$1 = [
	number,
	number,
	number
];
interface RectAreaRef {
	/** Rectangle corners in order: bottom-left, bottom-right, top-right, top-left */
	corners: [
		Vec3$1,
		Vec3$1,
		Vec3$1,
		Vec3$1
	];
}
type RectAreaArg = RectAreaRef | Rectangle2D;
/**
 * Build an arc bridge between two rectangular areas.
 *
 * @param rectA - First rectangle (2D Rectangle2D or 3D corners)
 * @param rectB - Second rectangle (2D Rectangle2D or 3D corners)
 * @param segments - Number of arc segments (more = smoother)
 * @returns Shape — the arc surface as a thin solid
 */
declare function arcBridgeBetweenRects(rectA: RectAreaArg, rectB: RectAreaArg, segments?: number): Shape;
type PointArg$1 = [
	number,
	number
] | [
	number,
	number,
	number
] | Point2D;
interface DimOpts {
	offset?: number;
	label?: string;
	color?: string;
	component?: string | string[];
	currentComponent?: boolean;
}
/**
 * Add a dimension annotation between two points.
 */
declare function dim(from: PointArg$1, to: PointArg$1, opts?: DimOpts): void;
/**
 * Add a dimension annotation along a Line2D.
 */
declare function dimLine(l: Line2D, opts?: DimOpts): void;
type Vec2 = [
	number,
	number
];
type Vec3$2 = [
	number,
	number,
	number
];
interface Spline2DOptions {
	/** Closed loop (default true). */
	closed?: boolean;
	/** Catmull-Rom tension in [0, 1]. 0 = very round, 1 = linear-ish. Default 0.5. */
	tension?: number;
	/** Samples per segment (minimum 3). Default 16. */
	samplesPerSegment?: number;
	/**
	 * For open splines, provide stroke width to return a solid Sketch.
	 * If omitted for open splines, an error is thrown.
	 */
	strokeWidth?: number;
	/** Stroke join for open splines. Default 'Round'. */
	join?: "Round" | "Square";
}
interface Spline3DOptions {
	/** Closed loop (default false). */
	closed?: boolean;
	/** Catmull-Rom tension in [0, 1]. 0 = very round, 1 = linear-ish. Default 0.5. */
	tension?: number;
}
interface LoftOptions {
	/** Marching-grid edge length for level-set meshing. Smaller = finer. */
	edgeLength?: number;
	/** Optional extra bounds padding. */
	boundsPadding?: number;
}
interface SweepOptions {
	/** Number of samples when path is a Curve3D. Default 48. */
	samples?: number;
	/** Marching-grid edge length for level-set meshing. Smaller = finer. */
	edgeLength?: number;
	/** Optional extra bounds padding. */
	boundsPadding?: number;
	/**
	 * Preferred "up" vector for local profile frame.
	 * Auto fallback is used near parallel segments.
	 */
	up?: Vec3$2;
}
declare class Curve3D {
	readonly points: Vec3$2[];
	readonly closed: boolean;
	readonly tension: number;
	constructor(points: Vec3$2[], options?: Spline3DOptions);
	sampleBySegment(samplesPerSegment?: number): Vec3$2[];
	sample(count?: number): Vec3$2[];
	pointAt(t: number): Vec3$2;
	tangentAt(t: number): Vec3$2;
	length(samples?: number): number;
}
/**
 * Create a smooth 2D spline sketch from control points.
 *
 * - Closed spline returns a filled profile.
 * - Open spline requires strokeWidth to return a solid sketch.
 */
declare function spline2d(points: Vec2[], options?: Spline2DOptions): Sketch;
/** Create a reusable 3D spline curve object. */
declare function spline3d(points: Vec3$2[], options?: Spline3DOptions): Curve3D;
/**
 * Loft between sketches along Z stations.
 *
 * Profiles can differ in topology/vertex count: interpolation is done on
 * signed-distance fields and meshed with level-set extraction.
 */
declare function loft(profiles: Sketch[], heights: number[], options?: LoftOptions): Shape;
/**
 * Sweep a 2D profile along a 3D path.
 *
 * Path can be:
 * - `Curve3D` from spline3d(...)
 * - array of [x,y,z] points (polyline)
 *
 * The profile is interpreted in the local frame normal plane (x,y axes).
 */
declare function sweep(profile: Sketch, path: Curve3D | Vec3$2[], options?: SweepOptions): Shape;
interface SvgImportOptions {
	/**
	 * Which geometry channels to include:
	 * - `auto`: prefer fills; if no fill geometry exists, fall back to strokes
	 * - `fill`: import only filled regions
	 * - `stroke`: import only stroke geometry
	 * - `fill-and-stroke`: include both
	 */
	include?: "auto" | "fill" | "stroke" | "fill-and-stroke";
	/** Keep all disconnected regions, or only the largest. */
	regionSelection?: "all" | "largest";
	/** Keep at most this many regions (largest-first). */
	maxRegions?: number;
	/** Drop regions below this absolute area threshold. */
	minRegionArea?: number;
	/** Drop regions below this ratio of largest-region area. */
	minRegionAreaRatio?: number;
	/**
	 * Curve flattening tolerance in SVG user units.
	 * Smaller = more segments, higher fidelity.
	 */
	flattenTolerance?: number;
	/** Minimum segment count for arc discretization. */
	arcSegments?: number;
	/** Global scale applied after SVG parsing. */
	scale?: number;
	/**
	 * Maximum imported sketch width.
	 * If exceeded, geometry is uniformly downscaled to fit.
	 */
	maxWidth?: number;
	/**
	 * Maximum imported sketch height.
	 * If exceeded, geometry is uniformly downscaled to fit.
	 */
	maxHeight?: number;
	/**
	 * Recenter imported geometry so its 2D bounds center is at CAD origin.
	 */
	centerOnOrigin?: boolean;
	/** Simplification tolerance for final sketch cleanup. */
	simplify?: number;
	/**
	 * Flip SVG Y-down coordinates to CAD Y-up.
	 * Enabled by default.
	 */
	invertY?: boolean;
}
interface TextOptions {
	/**
	 * Cap height of the text in model units.
	 * All other dimensions (stroke weight, spacing) scale proportionally.
	 * @default 10
	 */
	size?: number;
	/**
	 * Extra space between characters in model units.
	 * Negative values tighten the tracking.
	 * @default 0
	 */
	letterSpacing?: number;
	/**
	 * Horizontal alignment relative to x = 0.
	 * - `'left'`   — left edge at x = 0 (default)
	 * - `'center'` — centred on x = 0
	 * - `'right'`  — right edge at x = 0
	 * @default 'left'
	 */
	align?: "left" | "center" | "right";
	/**
	 * Vertical alignment relative to y = 0.
	 * - `'baseline'` — y = 0 is the text baseline (bottom of capital letters)
	 * - `'center'`   — y = 0 is the vertical midpoint of the cap height
	 * - `'top'`      — y = 0 is the top of capital letters
	 * @default 'baseline'
	 */
	baseline?: "baseline" | "center" | "top";
}
/**
 * Build a 2-D filled Sketch from a text string.
 *
 * The Sketch origin is at the left end of the text baseline by default (see
 * `align` and `baseline` options to adjust placement).  All characters are
 * drawn using the built-in "Forge Mono" geometric font — a clean, angular,
 * monoline typeface designed to extrude and engrave crisply.
 *
 * @example
 * // Extruded nameplate
 * text2d('FORGE CAD', { size: 8 }).extrude(1.2)
 *
 * @example
 * // Centered label on the XY plane
 * text2d('V 2.0', { size: 6, align: 'center', baseline: 'center' })
 */
declare function text2d(content: string, options?: TextOptions): Sketch;
/** Returns the rendered width of a string in model units (same options as text2d). */
declare function textWidth(content: string, options?: Pick<TextOptions, "size" | "letterSpacing">): number;
type GeometryBackend = "manifold" | "occt" | "hybrid" | "unknown";
type GeometryRepresentation = "mesh-solid" | "brep-solid" | "surface" | "mixed";
type GeometryFidelity = "kernel-native" | "sampled" | "deformed" | "mixed" | "unknown";
type GeometryTopology = "none" | "synthetic" | "kernel";
type GeometrySource = "primitive" | "extrude" | "revolve" | "boolean" | "sheet-metal" | "shell" | "fillet" | "chamfer" | "hull" | "level-set" | "loft" | "sweep" | "deform" | "unknown";
interface GeometryInfo {
	backend: GeometryBackend;
	representation: GeometryRepresentation;
	fidelity: GeometryFidelity;
	topology: GeometryTopology;
	sources: GeometrySource[];
}
interface ShapeLike {
	toShape(): Shape;
}
type ShapeOperandInput = Shape | ShapeLike | readonly (Shape | ShapeLike)[];
type ShapeRuntimePayload = ShapeBackend | Manifold;
type ShapeAnchorTarget = Shape | {
	referencePoint(ref: string): [
		number,
		number,
		number
	];
} | {
	_bbox(): {
		min: number[];
		max: number[];
	};
};
type RotationPointLike = PlacementAnchorLike | Vec3;
/** Thin immutable wrapper around a runtime geometry backend payload. */
declare class Shape {
	colorHex: string | undefined;
	constructor(payload: ShapeRuntimePayload, color?: string, geometryInfo?: Partial<GeometryInfo>);
	/** Set the color of this shape (hex string, e.g. "#ff0000") */
	setColor(value: string | undefined): Shape;
	/** Alias for setColor */
	color(value: string | undefined): Shape;
	/** Return a new Shape wrapper for explicit duplication in scripts. */
	clone(): Shape;
	/** Alias for clone() */
	duplicate(): Shape;
	/** Inspect which backend/representation produced this solid. */
	geometryInfo(): GeometryInfo;
	/** Attach named placement references that survive normal transforms and imports. */
	withReferences(refs: PlacementReferenceInput): Shape;
	/** List named placement references carried by this shape. */
	referenceNames(kind?: PlacementReferenceKind): string[];
	/** Resolve a named placement reference or built-in anchor to a 3D point. */
	referencePoint(ref: PlacementAnchorLike): [
		number,
		number,
		number
	];
	/** Resolve a defended semantic face by name on compile-covered shapes. */
	face(name: string): FaceRef;
	/** List defended semantic face names currently available on this shape. */
	faceNames(): string[];
	/** Get the transformation history for a specific face. */
	faceHistory(name: string): FaceTransformationHistory;
	/** Translate the shape so the given reference lands on the target coordinate. */
	placeReference(ref: PlacementAnchorLike, target: [
		number,
		number,
		number
	], offset?: [
		number,
		number,
		number
	]): Shape;
	translate(x: number, y: number, z: number): Shape;
	/** Move so bounding box min corner is at the given global coordinate */
	moveTo(x: number, y: number, z: number): Shape;
	/** Move so bounding box min corner is at target's bounding box min + (x, y, z) offset */
	moveToLocal(target: Shape | {
		toShape(): Shape;
	}, x: number, y: number, z: number): Shape;
	rotate(x: number, y: number, z: number): Shape;
	/** Apply a 4x4 affine transform matrix (column-major) or a Transform object. */
	transform(m: Mat4 | Transform): Shape;
	scale(v: number | [
		number,
		number,
		number
	]): Shape;
	mirror(normal: [
		number,
		number,
		number
	]): Shape;
	/**
	 * Reorient a shape so its primary axis (Z) points along the given direction.
	 * Useful for laying cylinders/extrusions along X or Y without thinking about Euler angles.
	 *
	 * Example: cylinder(40, 5).pointAlong([1, 0, 0]) — lays cylinder along X
	 */
	pointAlong(direction: [
		number,
		number,
		number
	]): Shape;
	/**
	 * Rotate around an arbitrary axis through a pivot point.
	 * Equivalent to: translate(-pivot) → rotate around axis → translate(+pivot)
	 */
	rotateAround(axis: [
		number,
		number,
		number
	], angleDeg: number, pivot?: [
		number,
		number,
		number
	]): Shape;
	/**
	 * Rotate around an axis until a moving point reaches the target line/plane defined by the axis and target point.
	 * `movingPoint` / `targetPoint` may be raw world points or this shape's anchors/references.
	 */
	rotateAroundTo(axis: [
		number,
		number,
		number
	], pivot: [
		number,
		number,
		number
	], movingPoint: RotationPointLike, targetPoint: RotationPointLike, options?: RotateAroundToOptions): Shape;
	/** Mark edges for smoothing based on angle. Call refine() after to apply. */
	smoothOut(minSharpAngle?: number, minSmoothness?: number): Shape;
	/** Subdivide mesh, interpolating smooth surfaces set by smoothOut(). */
	refine(n: number): Shape;
	/** Subdivide until edges are shorter than length. */
	refineToLength(length: number): Shape;
	/** Subdivide until surface is within tolerance of smooth surface. */
	refineToTolerance(tolerance: number): Shape;
	/** Warp vertices with a function. */
	warp(fn: (vert: [
		number,
		number,
		number
	]) => void): Shape;
	/** Unwrap TrackedShape (or any object with toShape()) without circular import. */
	private static _unwrap;
	add(...others: ShapeOperandInput[]): Shape;
	subtract(...others: ShapeOperandInput[]): Shape;
	intersect(...others: ShapeOperandInput[]): Shape;
	/** Split into [inside, outside] by another shape. */
	split(cutter: Shape | {
		toShape(): Shape;
	}): [
		Shape,
		Shape
	];
	/** Split by infinite plane. Returns [positive-side, negative-side]. */
	splitByPlane(normal: [
		number,
		number,
		number
	], originOffset?: number): [
		Shape,
		Shape
	];
	/** Keep the positive side of the plane and discard the opposite side. */
	trimByPlane(normal: [
		number,
		number,
		number
	], originOffset?: number): Shape;
	/** Hollow out compile-covered boxes, cylinders, and straight extrudes.
	 * `openFaces` names any subset of the base shape's faces to leave open (no wall).
	 * Box bases accept any of: top, bottom, front (=side-bottom), back (=side-top),
	 * left (=side-left), right (=side-right), or the raw internal names.
	 * Cylinder and extrude bases accept top and bottom only.
	 */
	shell(thickness: number, opts?: {
		openFaces?: string[];
	}): Shape;
	/** Convex hull of this shape. */
	hull(): Shape;
	/** Reduce mesh complexity. Vertices closer than tolerance are merged. */
	simplify(tolerance?: number): Shape;
	boundingBox(): unknown;
	volume(): number;
	surfaceArea(): number;
	/** Minimum distance between this shape and another. */
	minGap(other: Shape | {
		toShape(): Shape;
	}, searchLength: number): number;
	isEmpty(): boolean;
	numTri(): number;
	/** Extract triangle mesh for Three.js rendering */
	getMesh(): unknown;
	/** Slice the runtime solid by a plane normal to local Z at the given offset. */
	slice(offset?: number): unknown;
	/** Orthographically project the runtime solid onto the local XY plane. */
	project(): unknown;
	/** Position this shape relative to another using named 3D anchor points */
	attachTo(target: ShapeAnchorTarget, targetAnchor: PlacementAnchorLike, selfAnchor?: PlacementAnchorLike, offset?: [
		number,
		number,
		number
	]): Shape;
	/**
	 * Place this shape on a face of a parent shape.
	 *
	 * Think of it like sticking a label on a box surface:
	 * - `face` picks which surface ('front', 'back', 'top', etc.)
	 * - `u, v` position within that face's 2D plane (from center)
	 *   - front/back: u = left/right (X), v = up/down (Z)
	 *   - left/right: u = forward/back (Y), v = up/down (Z)
	 *   - top/bottom: u = left/right (X), v = forward/back (Y)
	 * - `protrude` = how far the child sticks out (positive = outward from face)
	 */
	onFace(parent: ShapeAnchorTarget, face: "front" | "back" | "left" | "right" | "top" | "bottom", opts?: {
		u?: number;
		v?: number;
		protrude?: number;
	}): Shape;
}
/**
 * Declare a parameter. Returns the current value (default or overridden).
 * Each call registers the param for UI generation.
 */
declare function param(name: string, defaultValue: number, opts?: {
	min?: number;
	max?: number;
	step?: number;
	unit?: string;
	integer?: boolean;
	reverse?: boolean;
}): number;
/**
 * Declare a boolean parameter. Returns the current boolean value.
 * Renders as a checkbox in the UI.
 */
declare function boolParam(name: string, defaultValue: boolean): boolean;
type GroupChild = Shape | Sketch | TrackedShape | ShapeGroup;
interface NamedGroupChild {
	name: string;
	shape?: Shape | TrackedShape | ShapeGroup;
	sketch?: Sketch;
	group?: GroupInput[];
}
type GroupInput = GroupChild | NamedGroupChild;
declare class ShapeGroup {
	readonly children: GroupChild[];
	readonly childNames: Array<string | undefined>;
	constructor(children: GroupChild[], childNames?: Array<string | undefined>);
	childName(index: number): string | undefined;
	/**
	 * Return the named child by name. Throws if not found.
	 * Useful when importing a multipart group and working on components individually.
	 */
	child(name: string): GroupChild;
	/** Apply fn to all children, producing a new ShapeGroup that also copies placement refs. */
	private mapChildren;
	/** Apply fn to all children and also transform placement refs by the given matrix. */
	private mapChildrenTransform;
	/** Return a deep-cloned ShapeGroup tree (refs copied). */
	clone(): ShapeGroup;
	/** Alias for clone() */
	duplicate(): ShapeGroup;
	translate(x: number, y: number, z: number): ShapeGroup;
	/** Compute combined bounding box of all 3D children */
	private _bbox;
	boundingBox(): {
		min: [
			number,
			number,
			number
		];
		max: [
			number,
			number,
			number
		];
	};
	private resolveRotatePoint;
	/** Move so combined bounding box min corner is at the given global coordinate */
	moveTo(x: number, y: number, z: number): ShapeGroup;
	/** Move so combined bounding box min corner is at target's bounding box min + (x, y, z) offset */
	moveToLocal(target: Shape | TrackedShape | ShapeGroup, x: number, y: number, z: number): ShapeGroup;
	attachTo(target: Shape | TrackedShape | ShapeGroup, targetAnchor: Anchor3D | string, selfAnchor?: Anchor3D, offset?: [
		number,
		number,
		number
	]): ShapeGroup;
	/**
	 * Place this group on a face of a parent shape.
	 * See Shape.onFace() for full documentation.
	 */
	onFace(parent: Shape | TrackedShape | ShapeGroup, face: "front" | "back" | "left" | "right" | "top" | "bottom", opts?: {
		u?: number;
		v?: number;
		protrude?: number;
	}): ShapeGroup;
	rotate(x: number, y: number, z: number): ShapeGroup;
	/**
	 * Rotate around an arbitrary axis through a pivot point.
	 * Sugar for: group.transform(Transform.rotationAxis(axis, angleDeg, pivot))
	 */
	rotateAround(axis: [
		number,
		number,
		number
	], angleDeg: number, pivot?: [
		number,
		number,
		number
	]): ShapeGroup;
	/**
	 * Rotate around an axis until a moving point reaches the target line/plane defined by the axis and target point.
	 * ShapeGroup string points use built-in anchors only.
	 */
	rotateAroundTo(axis: [
		number,
		number,
		number
	], pivot: [
		number,
		number,
		number
	], movingPoint: Anchor3D | [
		number,
		number,
		number
	], targetPoint: Anchor3D | [
		number,
		number,
		number
	], options?: RotateAroundToOptions): ShapeGroup;
	/**
	 * Reorient all 3D children so their primary axis (Z) points along direction.
	 * Sugar for a single group-wide axis rotation via Transform.rotationAxis(...).
	 */
	pointAlong(direction: [
		number,
		number,
		number
	]): ShapeGroup;
	/** Apply a 4x4 transform matrix or Transform object to all 3D children. */
	transform(m: Mat4 | Transform): ShapeGroup;
	scale(v: number | [
		number,
		number,
		number
	]): ShapeGroup;
	mirror(normal: [
		number,
		number,
		number
	]): ShapeGroup;
	color(hex: string): ShapeGroup;
	/**
	 * Attach named placement references to this group.
	 * References survive normal transforms (translate/rotate/scale/mirror/transform).
	 *
	 * ```javascript
	 * const bracket = group(
	 *   { name: 'Left', shape: leftShape },
	 *   { name: 'Right', shape: rightShape },
	 * ).withReferences({
	 *   points: { mountCenter: [0, 0, 0] },
	 * });
	 * ```
	 */
	withReferences(refs: PlacementReferenceInput): ShapeGroup;
	/** List named placement references carried by this group. */
	referenceNames(kind?: PlacementReferenceKind): string[];
	/**
	 * Resolve a named placement reference or built-in Anchor3D to a 3D point.
	 * Named refs take priority over built-in anchors.
	 */
	referencePoint(ref: PlacementAnchorLike): [
		number,
		number,
		number
	];
	/**
	 * Translate the group so the given reference lands on the target coordinate.
	 *
	 * ```javascript
	 * const placed = importGroup('bracket-assembly.forge.js')
	 *   .placeReference('mountCenter', [0, 0, 50]);
	 * ```
	 */
	placeReference(ref: PlacementAnchorLike, target: [
		number,
		number,
		number
	], offset?: [
		number,
		number,
		number
	]): ShapeGroup;
}
declare function group(...items: GroupInput[]): ShapeGroup;
type AssemblyPart = Shape | TrackedShape | ShapeGroup;
type JointType = "fixed" | "revolute" | "prismatic";
type JointState = Record<string, number | undefined>;
interface PartMetadata {
	material?: string;
	process?: string;
	tolerance?: string;
	qty?: number;
	notes?: string;
	densityKgM3?: number;
	massKg?: number;
	[key: string]: unknown;
}
interface PartOptions {
	transform?: TransformInput;
	metadata?: PartMetadata;
}
interface JointOptions {
	frame?: TransformInput;
	axis?: Vec3;
	min?: number;
	max?: number;
	default?: number;
	unit?: string;
	effort?: number;
	velocity?: number;
	damping?: number;
	friction?: number;
}
interface JointCouplingTerm {
	joint: string;
	ratio?: number;
}
interface JointCouplingOptions {
	terms: JointCouplingTerm[];
	offset?: number;
}
interface GearRatioLike {
	jointRatio: number;
}
interface GearCouplingOptions {
	ratio?: number;
	pair?: GearRatioLike;
	driverTeeth?: number;
	drivenTeeth?: number;
	mesh?: "external" | "internal" | "bevel" | "face";
	offset?: number;
}
interface PartRecord {
	name: string;
	part: AssemblyPart;
	base: Transform;
	metadata?: PartMetadata;
}
interface JointCouplingTermRecord {
	joint: string;
	ratio: number;
}
interface AssemblyPartDef {
	name: string;
	part: AssemblyPart;
	base: Transform;
	metadata?: PartMetadata;
}
interface AssemblyJointDef {
	name: string;
	type: JointType;
	parent: string;
	child: string;
	frame: Transform;
	axis: Vec3;
	min?: number;
	max?: number;
	defaultValue: number;
	unit?: string;
	effort?: number;
	velocity?: number;
	damping?: number;
	friction?: number;
}
interface AssemblyJointCouplingDef {
	joint: string;
	terms: JointCouplingTermRecord[];
	offset: number;
}
interface AssemblyDefinition {
	name: string;
	parts: AssemblyPartDef[];
	joints: AssemblyJointDef[];
	jointCouplings: AssemblyJointCouplingDef[];
}
interface BomRow {
	part: string;
	qty: number;
	material?: string;
	process?: string;
	tolerance?: string;
	notes?: string;
	metadata?: PartMetadata;
}
interface CollisionOptions {
	parts?: string[];
	ignorePairs?: Array<[
		string,
		string
	]>;
	minOverlapVolume?: number;
}
interface CollisionFinding {
	partA: string;
	partB: string;
	overlapVolume: number;
}
interface JointSweepFrame {
	value: number;
	collisions: CollisionFinding[];
	warnings: string[];
}
declare function bomToCsv(rows: BomRow[]): string;
declare class SolvedAssembly {
	readonly name: string;
	private readonly parts;
	private readonly transforms;
	private readonly jointValues;
	private readonly solveWarnings;
	constructor(name: string, parts: Map<string, PartRecord>, transforms: Map<string, Transform>, jointValues: JointState, solveWarnings: string[]);
	warnings(): string[];
	getJointState(): JointState;
	getTransform(partName: string): Transform;
	getPart(partName: string): AssemblyPart;
	toScene(): Array<{
		name: string;
		shape?: Shape;
		group?: Array<{
			name: string;
			shape: Shape;
		}>;
		metadata?: PartMetadata;
	}>;
	bom(): BomRow[];
	bomCsv(): string;
	collisionReport(options?: CollisionOptions): CollisionFinding[];
	minClearance(partA: string, partB: string, searchLength?: number): number;
}
declare class Assembly {
	readonly name: string;
	private readonly parts;
	private readonly joints;
	private readonly jointCouplings;
	private _refs;
	constructor(name?: string);
	/**
	 * Attach named placement reference points to this assembly.
	 * These are surfaced automatically on the ImportedAssembly when this file is
	 * imported with importAssembly(), so consumers can use placeReference() without
	 * re-declaring them.
	 * Returns `this` for chaining.
	 */
	withReferences(refs: Pick<PlacementReferenceInput, "points">): Assembly;
	/** @internal — used by importAssembly() to seed ImportedAssembly refs. */
	getReferences(): PlacementReferences;
	/** Add a virtual reference frame (no geometry) to the assembly graph. */
	addFrame(name: string, options?: PartOptions): Assembly;
	addPart(name: string, part: AssemblyPart, options?: PartOptions): Assembly;
	addJoint(name: string, type: JointType, parent: string, child: string, options?: JointOptions): Assembly;
	addRevolute(name: string, parent: string, child: string, options?: JointOptions): Assembly;
	addPrismatic(name: string, parent: string, child: string, options?: JointOptions): Assembly;
	addFixed(name: string, parent: string, child: string, options?: JointOptions): Assembly;
	addJointCoupling(jointName: string, options: JointCouplingOptions): Assembly;
	addGearCoupling(drivenJointName: string, driverJointName: string, options?: GearCouplingOptions): Assembly;
	private assertJointCouplingsAcyclic;
	solve(state?: JointState): SolvedAssembly;
	sweepJoint(jointName: string, from: number, to: number, steps: number, baseState?: JointState, collisionOptions?: CollisionOptions): JointSweepFrame[];
	describe(): AssemblyDefinition;
}
declare function assembly(name?: string): Assembly;
interface MergeIntoOptions {
	/**
	 * Prefix applied to every part name and joint name from the sub-assembly.
	 * E.g. prefix "Left Arm" turns part "Base" into "Left Arm.Base".
	 * Strongly recommended to avoid name collisions when merging multiple instances.
	 */
	prefix?: string;
	/** Part name in the parent assembly to attach the sub-assembly root to. */
	mountParent: string;
	/** Name for the new mount joint in the parent graph. */
	mountJoint: string;
	/** Joint type for the mount connection (default: 'fixed'). */
	mountType?: JointType;
	/** Frame, axis, limits, and other options for the mount joint. */
	mountOptions?: JointOptions;
}
/**
 * Wraps an imported Assembly, giving access to named parts and group conversion
 * without losing the kinematic structure.
 *
 * Supports placement references (`.withReferences()` / `.placeReference()`) so
 * sub-assemblies can be positioned the same way as imported parts and groups.
 */
declare class ImportedAssembly {
	private readonly _assembly;
	private readonly _refs;
	private readonly _offset;
	constructor(_assembly: Assembly, _refs?: PlacementReferences, _offset?: readonly [
		number,
		number,
		number
	]);
	/** The underlying Assembly — use for sweepJoint, addPart into parent, etc. */
	get assembly(): Assembly;
	/** Solve the assembly at the given joint state (defaults to each joint's default value). */
	solve(state?: JointState): SolvedAssembly;
	/**
	 * Return a specific named part positioned at the given joint state, with any
	 * stored placement offset applied.
	 */
	part(name: string, state?: JointState): AssemblyPart;
	/**
	 * Convert all assembly parts to a ShapeGroup with named children.
	 * Child names match the part names used in the assembly.
	 * Any stored placement offset and placement references are forwarded to the group.
	 */
	toGroup(state?: JointState): ShapeGroup;
	/**
	 * Attach named placement reference points to this assembly.
	 * Points are simple 3D coordinates (relative to the assembly's own origin).
	 * Returns a new ImportedAssembly — does not mutate.
	 */
	withReferences(refs: Pick<PlacementReferenceInput, "points">): ImportedAssembly;
	/** List all attached placement reference names. */
	referenceNames(kind?: PlacementReferenceKind): string[];
	/**
	 * Translate the assembly so the named reference point lands on `target`.
	 * Returns a new ImportedAssembly — does not mutate.
	 * All point refs are translated by the same delta.
	 */
	placeReference(ref: string, target: [
		number,
		number,
		number
	], offset?: [
		number,
		number,
		number
	]): ImportedAssembly;
	/**
	 * Flatten this sub-assembly's parts and joints into `parent`, then wire a
	 * mount joint connecting `mountParent` (a part already in `parent`) to the
	 * sub-assembly root.
	 *
	 * All part names and joint names from the sub-assembly are prefixed with
	 * `"${options.prefix}."` to avoid collisions. After the merge you can drive
	 * sub-assembly joints from the parent: `parent.solve({ "Left Arm.shoulder": 45 })`.
	 *
	 * Throws if the sub-assembly has multiple root parts (connect them with addFixed first).
	 *
	 * Returns `parent` for chaining.
	 */
	mergeInto(parent: Assembly, options: MergeIntoOptions): Assembly;
}
interface RevoluteJointOpts {
	axis?: [
		number,
		number,
		number
	];
	min?: number;
	max?: number;
	default?: number;
	unit?: string;
	reverse?: boolean;
}
/**
 * Create a revolute (hinge) joint. Auto-creates a param slider and rotates the shape.
 *
 * @param name - Display name for the angle parameter
 * @param shape - The shape to rotate
 * @param pivot - The pivot point [x, y, z]
 * @param opts - Joint options (axis, min/max angle, default)
 * @returns The rotated shape
 */
declare function joint(name: string, shape: Shape, pivot: [
	number,
	number,
	number
], opts?: RevoluteJointOpts): Shape;
type CutPlaneExcludeInput = string | string[];
interface CutPlaneOptions {
	/** Optional offset along the plane normal (primarily for object-form overload). */
	offset?: number;
	/** Object names to keep uncut for this plane. */
	exclude?: CutPlaneExcludeInput;
}
/**
 * Define a named section/cut plane. Appears as a toggle in the View Panel.
 * When enabled, geometry on the positive side of the plane is clipped away.
 *
 * @param name   Display name in the View Panel
 * @param normal Plane normal direction [x, y, z] — geometry on this side is removed
 * @param offset Distance from origin along the normal. Default: 0
 * @param options.exclude Names of returned scene objects to keep uncut for this plane
 */
declare function cutPlane(name: string, normal: [
	number,
	number,
	number
], offset?: number, options?: CutPlaneOptions): void;
declare function cutPlane(name: string, normal: [
	number,
	number,
	number
], options?: CutPlaneOptions): void;
interface BomOpts {
	/**
	 * Quantity unit label, e.g. "mm", "pieces", "kg".
	 * Default: "pieces"
	 */
	unit?: string;
	/**
	 * Optional explicit grouping key used during report aggregation.
	 */
	key?: string;
}
/**
 * Add a bill-of-materials entry.
 *
 * @param quantity numeric quantity (e.g. 1200)
 * @param description human-readable item text (e.g. "iron tube with dimensions 20 x 20")
 * @param opts optional unit and explicit grouping key
 */
declare function bom(quantity: number, description: string, opts?: BomOpts): void;
interface RobotLinkExportOptions {
	massKg?: number;
	densityKgM3?: number;
	collision?: "visual" | "none";
}
interface RobotJointExportOptions {
	effort?: number;
	velocity?: number;
	damping?: number;
	friction?: number;
}
interface RobotDiffDrivePluginOptions {
	leftJoints: string[];
	rightJoints: string[];
	wheelSeparationMm: number;
	wheelRadiusMm: number;
	topic?: string;
	odomTopic?: string;
	tfTopic?: string;
	frameId?: string;
	odomFrameId?: string;
	maxLinearVelocity?: number;
	maxAngularVelocity?: number;
	linearAcceleration?: number;
	angularAcceleration?: number;
}
interface RobotJointStatePublisherOptions {
	enabled?: boolean;
	joints?: string[];
	topic?: string;
	updateRate?: number;
}
type RobotPose6 = [
	number,
	number,
	number,
	number,
	number,
	number
];
interface RobotWorldKeyboardTeleopOptions {
	enabled?: boolean;
	linearStep?: number;
	angularStep?: number;
}
interface RobotWorldOptions {
	name?: string;
	generateDemoWorld?: boolean;
	spawnPose?: RobotPose6;
	keyboardTeleop?: RobotWorldKeyboardTeleopOptions;
}
interface RobotExportOptions {
	assembly: Assembly;
	modelName?: string;
	state?: JointState;
	static?: boolean;
	selfCollide?: boolean;
	allowAutoDisable?: boolean;
	links?: Record<string, RobotLinkExportOptions>;
	joints?: Record<string, RobotJointExportOptions>;
	plugins?: {
		diffDrive?: RobotDiffDrivePluginOptions;
		jointStatePublisher?: RobotJointStatePublisherOptions;
	};
	world?: RobotWorldOptions;
}
interface CollectedRobotExport {
	modelName: string;
	assembly: AssemblyDefinition;
	state: JointState;
	static: boolean;
	selfCollide: boolean;
	allowAutoDisable: boolean;
	links: Record<string, RobotLinkExportOptions>;
	joints: Record<string, RobotJointExportOptions>;
	plugins: {
		diffDrive?: RobotDiffDrivePluginOptions;
		jointStatePublisher?: RobotJointStatePublisherOptions;
	};
	world: RobotWorldOptions | null;
}
declare function robotExport(options: RobotExportOptions): CollectedRobotExport;
interface ShapeLike$1 {
	boundingBox(): {
		min: number[];
		max: number[];
	};
	isEmpty(): boolean;
	volume(): number;
	surfaceArea(): number;
	minGap(other: ShapeLike$1, searchLength: number): number;
}
interface FaceRefLike {
	normal: [
		number,
		number,
		number
	];
	center: [
		number,
		number,
		number
	];
}
declare const verify: {
	/**
	 * Custom predicate check.
	 *
	 * @param label  Short name shown in the panel ("gear clearance")
	 * @param check  Function that returns true (pass) or false (fail)
	 * @param message  Optional extra context shown on failure
	 */
	that(label: string, check: () => boolean, message?: string): void;
	/**
	 * Check that two numbers are approximately equal (within tolerance).
	 */
	equal(label: string, actual: number, expected: number, tolerance?: number, message?: string): void;
	/**
	 * Check that two numbers are NOT equal (differ by more than tolerance).
	 */
	notEqual(label: string, actual: number, unexpected: number, tolerance?: number, message?: string): void;
	/** Check that actual > min. */
	greaterThan(label: string, actual: number, min: number, message?: string): void;
	/** Check that actual < max. */
	lessThan(label: string, actual: number, max: number, message?: string): void;
	/** Check that min <= actual <= max. */
	inRange(label: string, actual: number, min: number, max: number, message?: string): void;
	/**
	 * Check that the bounding-box centers of two shapes coincide within tolerance (mm).
	 */
	centersCoincide(label: string, a: ShapeLike$1, b: ShapeLike$1, tolerance?: number): void;
	/**
	 * Check that two shapes do not collide (minGap > 0).
	 *
	 * @param searchLength  Search radius for minGap (mm, default 1.0)
	 */
	notColliding(label: string, a: ShapeLike$1, b: ShapeLike$1, searchLength?: number): void;
	/**
	 * Check that a minimum clearance gap exists between two shapes.
	 */
	minClearance(label: string, a: ShapeLike$1, b: ShapeLike$1, minGap: number, searchLength?: number): void;
	/**
	 * Check that two face normals are parallel (within toleranceDeg degrees).
	 */
	parallel(label: string, faceA: FaceRefLike, faceB: FaceRefLike, toleranceDeg?: number): void;
	/**
	 * Check that two face normals are perpendicular (within toleranceDeg degrees).
	 */
	perpendicular(label: string, faceA: FaceRefLike, faceB: FaceRefLike, toleranceDeg?: number): void;
	/**
	 * Check that a face is coplanar with (same plane as) another face,
	 * meaning they are parallel AND their centers lie on the same plane.
	 */
	coplanar(label: string, faceA: FaceRefLike, faceB: FaceRefLike, toleranceDeg?: number, toleranceMm?: number): void;
	/**
	 * Check that a face center lies at a specific position (within toleranceMm).
	 */
	faceAt(label: string, face: FaceRefLike, expectedPos: [
		number,
		number,
		number
	], toleranceMm?: number): void;
	/**
	 * Check that two face normals point in the same direction (not antiparallel).
	 * Stricter than parallel — both |angle| AND sign must match.
	 */
	sameDirection(label: string, faceA: FaceRefLike, faceB: FaceRefLike, toleranceDeg?: number): void;
	/**
	 * Check that a shape is empty.
	 */
	isEmpty(label: string, shape: ShapeLike$1, message?: string): void;
	/**
	 * Check that a shape is NOT empty.
	 */
	notEmpty(label: string, shape: ShapeLike$1, message?: string): void;
	/**
	 * Check that a shape's volume is approximately equal to expected (mm³).
	 *
	 * @param expected  Expected volume in mm³
	 * @param tolerance  Absolute tolerance in mm³ (default 1.0)
	 */
	volumeApprox(label: string, shape: ShapeLike$1, expected: number, tolerance?: number): void;
	/**
	 * Check that a shape's surface area is approximately equal to expected (mm²).
	 *
	 * @param expected  Expected surface area in mm²
	 * @param tolerance  Absolute tolerance in mm² (default 1.0)
	 */
	areaApprox(label: string, shape: ShapeLike$1, expected: number, tolerance?: number): void;
	/**
	 * Check that a shape's bounding box has approximately the given size.
	 *
	 * @param expectedSize  [sizeX, sizeY, sizeZ] in mm
	 * @param tolerance  Per-axis tolerance in mm (default 0.1)
	 */
	boundingBoxSize(label: string, shape: ShapeLike$1, expectedSize: [
		number,
		number,
		number
	], tolerance?: number): void;
};
type ExplodeAxis = "x" | "y" | "z";
type ExplodeDirection = "radial" | ExplodeAxis | [
	number,
	number,
	number
];
interface ExplodeDirective {
	/** Multiplier applied to `amount` for this node */
	stage?: number;
	/** Direction mode for this node */
	direction?: ExplodeDirection;
	/** Optional axis lock after direction is resolved */
	axisLock?: ExplodeAxis;
}
interface ExplodeConfigOptions {
	amount?: number;
	stages?: number[];
	mode?: ExplodeDirection;
	axisLock?: ExplodeAxis;
	byName?: Record<string, ExplodeDirective>;
	byPath?: Record<string, ExplodeDirective>;
}
type ExplodeViewDirection = ExplodeDirection;
interface ExplodeViewDirective extends ExplodeDirective {
}
interface ExplodeViewOptions {
	/** Set false to disable viewport explode offsets for this script output. */
	enabled?: boolean;
	/** Scales the UI explode amount. Default: 1 */
	amountScale?: number;
	/**
	 * Per-depth stage multipliers (depth 1 = first level).
	 * If depth exceeds this array, the last value is reused.
	 * Default when omitted: reciprocal depth (1, 1/2, 1/3, ...)
	 */
	stages?: number[];
	/** Global direction mode fallback. Default: 'radial' */
	mode?: ExplodeViewDirection;
	/** Global axis lock fallback. */
	axisLock?: ExplodeAxis;
	/** Per-object overrides by final object name. */
	byName?: Record<string, ExplodeViewDirective>;
	/** Per-tree-path overrides using slash-separated object tree segments. */
	byPath?: Record<string, ExplodeViewDirective>;
}
/**
 * Configure viewport exploded-view behavior for the current script execution.
 * Multiple calls merge; later values override earlier ones.
 */
declare function explodeView(options?: ExplodeViewOptions): void;
type JointViewType = "revolute" | "prismatic";
type JointViewAxis = [
	number,
	number,
	number
];
interface JointViewInput {
	name: string;
	child: string;
	parent?: string;
	type?: JointViewType;
	axis?: JointViewAxis;
	pivot?: [
		number,
		number,
		number
	];
	min?: number;
	max?: number;
	default?: number;
	unit?: string;
}
interface JointViewAnimationKeyframeInput {
	at: number;
	values: Record<string, number>;
}
interface JointViewAnimationInput {
	name: string;
	duration?: number;
	loop?: boolean;
	continuous?: boolean;
	keyframes: JointViewAnimationKeyframeInput[];
}
interface JointViewCouplingTermInput {
	joint: string;
	ratio?: number;
}
interface JointViewCouplingInput {
	joint: string;
	terms: JointViewCouplingTermInput[];
	offset?: number;
}
interface JointsViewOptions {
	enabled?: boolean;
	joints?: JointViewInput[];
	couplings?: JointViewCouplingInput[];
	animations?: JointViewAnimationInput[];
	defaultAnimation?: string;
}
/**
 * Configure runtime joint controls that animate object transforms in the viewport
 * without re-running the script.
 */
declare function jointsView(options?: JointsViewOptions): void;
interface JointOverlayViewConfigOptions {
	enabled?: boolean;
	axisColor?: string;
	axisCoreColor?: string;
	arcColor?: string;
	zeroColor?: string;
	arcVisualLimitDeg?: number;
	axisLengthScale?: number;
	axisLengthMin?: number;
	axisLineRadiusScale?: number;
	axisLineRadiusMin?: number;
	axisLineRadiusMax?: number;
	spokeLineRadiusScale?: number;
	spokeLineRadiusMin?: number;
	spokeLineRadiusMax?: number;
	arcLineRadiusScale?: number;
	arcLineRadiusMin?: number;
	arcLineRadiusMax?: number;
	axisDotRadiusScale?: number;
	axisDotRadiusMin?: number;
	axisArrowRadiusScale?: number;
	axisArrowRadiusMin?: number;
	axisArrowLengthScale?: number;
	axisArrowLengthMin?: number;
	axisArrowOffsetFactor?: number;
	arcRadiusScale?: number;
	arcRadiusMin?: number;
	arcDotRadiusScale?: number;
	arcDotRadiusMin?: number;
	arcArrowRadiusScale?: number;
	arcArrowRadiusMin?: number;
	arcArrowLengthScale?: number;
	arcArrowLengthMin?: number;
	arcArrowOffsetFactor?: number;
	arcStepDeg?: number;
	arcMinSteps?: number;
	arcTubeSegmentsMin?: number;
	arcTubeSegmentsFactor?: number;
	arcTubeRadialSegments?: number;
}
interface ViewConfigOptions {
	jointOverlay?: JointOverlayViewConfigOptions;
}
/**
 * Configure runtime viewport visuals for the current script execution.
 * Multiple calls merge; later values override earlier ones.
 */
declare function viewConfig(options?: ViewConfigOptions): void;
interface ShapeFeatureExtentSideOptions {
	depth?: number;
	upToFace?: SketchFaceTarget | FaceRef;
	through?: boolean;
}
interface ShapeFeatureExtentOptions {
	forward: ShapeFeatureExtentSideOptions;
	reverse?: ShapeFeatureExtentSideOptions;
}
interface ShapeHoleThreadOptions {
	designation?: string;
	pitch?: number;
	class?: string;
	handedness?: "right" | "left";
	depth?: number;
	modeled?: boolean;
}
interface ShapeHoleOptions {
	diameter: number;
	depth?: number;
	upToFace?: SketchFaceTarget | FaceRef;
	extent?: ShapeFeatureExtentOptions;
	u?: number;
	v?: number;
	counterbore?: {
		diameter: number;
		depth: number;
	};
	countersink?: {
		diameter: number;
		angleDeg?: number;
	};
	thread?: ShapeHoleThreadOptions;
}
interface ShapeCutoutOptions {
	depth?: number;
	upToFace?: SketchFaceTarget | FaceRef;
	extent?: ShapeFeatureExtentOptions;
	taperScale?: number | [
		number,
		number
	];
}
interface Shape {
	hole(faceOrRef: SketchFaceTarget | FaceRef, opts: ShapeHoleOptions): Shape;
	cutout(sketch: Sketch, opts?: ShapeCutoutOptions): Shape;
}
interface TrackedShape {
	hole(faceOrRef: SketchFaceTarget | FaceRef, opts: ShapeHoleOptions): Shape;
	cutout(sketch: Sketch, opts?: ShapeCutoutOptions): Shape;
}
interface SheetMetalOptions {
	panel: {
		width: number;
		height: number;
	};
	thickness: number;
	bendRadius: number;
	bendAllowance: {
		kFactor: number;
	};
	cornerRelief?: {
		kind?: "rect";
		size: number;
	};
}
interface SheetMetalFlangeOptions {
	length: number;
	angleDeg?: number;
}
interface SheetMetalCutoutOptions {
	u?: number;
	v?: number;
	selfAnchor?: Anchor;
}
interface SheetMetalCutoutOp {
	region: SheetMetalPlanarRegionName;
	sketch: Sketch;
	u: number;
	v: number;
	selfAnchor: Anchor;
}
declare class SheetMetalPart {
	private readonly model;
	private readonly cutouts;
	constructor(model: SheetMetalModel, cutouts?: readonly SheetMetalCutoutOp[]);
	flange(edge: SheetMetalEdge, options: SheetMetalFlangeOptions): SheetMetalPart;
	cutout(region: SheetMetalPlanarRegionName, sketch: Sketch, options?: SheetMetalCutoutOptions): SheetMetalPart;
	regionNames(): SheetMetalRegionName[];
	folded(): Shape;
	flatPattern(): Shape;
	private buildOutput;
}
declare function sheetMetal(options: SheetMetalOptions): SheetMetalPart;
declare function intersectWithPlane(shape: Shape, plane: PlaneSpec): Sketch;
declare function projectToPlane(shape: Shape, plane: PlaneSpec): Sketch;
declare function boltHole(diameter: number, depth: number): Shape;
type MetricSize = "M2" | "M2.5" | "M3" | "M4" | "M5" | "M6" | "M8" | "M10";
type FastenerFit = "close" | "normal" | "loose" | "tap";
interface FastenerHoleOptions {
	standard?: "iso-metric";
	size: MetricSize;
	fit?: FastenerFit;
	depth: number;
	counterbore?: {
		depth: number;
		diameter?: number;
	};
	countersink?: {
		diameter: number;
		angleDeg?: number;
	};
	center?: boolean;
	segments?: number;
}
declare function fastenerHole(opts: FastenerHoleOptions): Shape;
declare function counterbore(holeDia: number, boreDia: number, boreDepth: number, totalDepth: number): Shape;
declare function tube(outerX: number, outerY: number, outerZ: number, wall: number): Shape;
declare function pipe(height: number, outerRadius: number, wall: number, segments?: number): Shape;
declare function hexNut(acrossFlats: number, height: number, holeDia: number): Shape;
declare function roundedBox(x: number, y: number, z: number, radius: number): Shape;
declare function bracket(width: number, height: number, depth: number, thick: number, holeDia?: number): Shape;
declare function holePattern(rows: number, cols: number, spacingX: number, spacingY: number, holeDia: number, depth: number): Shape;
interface TSlotProfileOptions {
	/** Outer profile size (square). */
	size?: number;
	/** Slot mouth width (the narrow opening at each side). */
	slotWidth?: number;
	/** Wider interior slot cavity width. Must be >= slotWidth. */
	slotInnerWidth?: number;
	/** Total slot depth from outer face inward. */
	slotDepth?: number;
	/** Depth of the narrow mouth before it widens into slotInnerWidth. */
	slotNeckDepth?: number;
	/** Outer shell wall thickness. */
	wall?: number;
	/** Central cross-web thickness. */
	web?: number;
	/** Center boss diameter (solid material around center bore). */
	centerBossDia?: number;
	/** Center bore diameter (for tapping/through-hole). Set 0 to disable. */
	centerBoreDia?: number;
	/** Outer corner radius. */
	outerCornerRadius?: number;
	/** Segment count used for circular features in 2D. */
	segments?: number;
}
interface TSlotExtrusionOptions extends TSlotProfileOptions {
	/** Center the extrusion around Z=0 instead of starting at Z=0. */
	center?: boolean;
}
declare function tSlotProfile(options?: TSlotProfileOptions): Sketch;
declare function tSlotExtrusion(length: number, options?: TSlotExtrusionOptions): Shape;
interface Profile2020BSlot6ProfileOptions {
	/** Slot mouth width. */
	slotWidth?: number;
	/** Wider inner slot width. */
	slotInnerWidth?: number;
	/** Slot depth from outer face. */
	slotDepth?: number;
	/** Depth of the narrow neck before widening into slotInnerWidth. */
	slotNeckDepth?: number;
	/** Center core bore diameter (set 0 to disable). */
	centerBoreDia?: number;
	/** Solid boss diameter around center bore (must exceed centerBoreDia when bore is enabled). */
	centerBossDia?: number;
	/** Width of diagonal ribs connecting center boss to corner regions. */
	diagonalWebWidth?: number;
	/** Outside corner radius. */
	outerCornerRadius?: number;
	/** Circle segment count. */
	segments?: number;
}
interface Profile2020BSlot6Options extends Profile2020BSlot6ProfileOptions {
	/** Center the extrusion around Z=0 instead of starting at Z=0. */
	center?: boolean;
}
declare function profile2020BSlot6Profile(options?: Profile2020BSlot6ProfileOptions): Sketch;
declare function profile2020BSlot6(length: number, options?: Profile2020BSlot6Options): Shape;
interface ExplodeNamedItem {
	name: string;
	shape?: Shape | TrackedShape | ShapeGroup;
	sketch?: Sketch;
	color?: string;
	group?: ExplodeItem[];
	explode?: ExplodeDirective;
}
type ExplodeItem = Shape | Sketch | TrackedShape | ShapeGroup | ExplodeNamedItem;
interface ExplodeOptions extends ExplodeConfigOptions {
}
declare function explode<T extends ExplodeItem[] | ShapeGroup>(items: T, options?: ExplodeOptions): T;
declare function pipeRoute(points: [
	number,
	number,
	number
][], radius: number, options?: {
	bendRadius?: number;
	wall?: number;
	segments?: number;
}): Shape;
declare function elbow(pipeRadius: number, bendRadius: number, angle?: number | {
	from?: [
		number,
		number,
		number
	];
	to?: [
		number,
		number,
		number
	];
	wall?: number;
	segments?: number;
}, options?: {
	wall?: number;
	segments?: number;
	from?: [
		number,
		number,
		number
	];
	to?: [
		number,
		number,
		number
	];
}): Shape;
interface SpurGearOptions {
	module: number;
	teeth: number;
	pressureAngleDeg?: number;
	faceWidth: number;
	backlash?: number;
	clearance?: number;
	addendum?: number;
	dedendum?: number;
	boreDiameter?: number;
	center?: boolean;
	segmentsPerTooth?: number;
}
declare function spurGear(options: SpurGearOptions): Shape;
interface SideGearOptions extends SpurGearOptions {
	side?: "top" | "bottom";
	toothHeight?: number;
}
interface FaceGearOptions extends SideGearOptions {
}
declare function sideGear(options: SideGearOptions): Shape;
declare function faceGear(options: FaceGearOptions): Shape;
interface RingGearOptions {
	module: number;
	teeth: number;
	pressureAngleDeg?: number;
	faceWidth: number;
	backlash?: number;
	clearance?: number;
	addendum?: number;
	dedendum?: number;
	rimWidth?: number;
	outerDiameter?: number;
	center?: boolean;
	segmentsPerTooth?: number;
}
declare function ringGear(options: RingGearOptions): Shape;
interface RackGearOptions {
	module: number;
	teeth: number;
	pressureAngleDeg?: number;
	faceWidth: number;
	backlash?: number;
	clearance?: number;
	addendum?: number;
	dedendum?: number;
	baseHeight?: number;
	center?: boolean;
}
declare function rackGear(options: RackGearOptions): Shape;
interface BevelGearOptions {
	module: number;
	teeth: number;
	pressureAngleDeg?: number;
	faceWidth: number;
	backlash?: number;
	clearance?: number;
	addendum?: number;
	dedendum?: number;
	boreDiameter?: number;
	pitchAngleDeg?: number;
	mateTeeth?: number;
	shaftAngleDeg?: number;
	center?: boolean;
	segmentsPerTooth?: number;
}
declare function bevelGear(options: BevelGearOptions): Shape;
interface GearPairSpec {
	module: number;
	teeth: number;
	pressureAngleDeg?: number;
	faceWidth?: number;
	backlash?: number;
	clearance?: number;
	addendum?: number;
	dedendum?: number;
	boreDiameter?: number;
	segmentsPerTooth?: number;
}
interface GearPairOptions {
	pinion: Shape | GearPairSpec;
	gear: Shape | GearPairSpec;
	backlash?: number;
	centerDistance?: number;
	place?: boolean;
	phaseDeg?: number;
}
interface GearPairDiagnostic {
	level: "info" | "warn" | "error";
	code: string;
	message: string;
}
interface GearPairResult {
	pinion: Shape;
	gear: Shape;
	centerDistance: number;
	centerDistanceNominal: number;
	backlash: number;
	pressureAngleDeg: number;
	workingPressureAngleDeg: number;
	contactRatio: number;
	jointRatio: number;
	speedReduction: number;
	diagnostics: GearPairDiagnostic[];
	status: "ok" | "warn" | "error";
}
declare function gearPair(options: GearPairOptions): GearPairResult;
interface GearMeshPlacement {
	pinionAxis: [
		number,
		number,
		number
	];
	gearAxis: [
		number,
		number,
		number
	];
	pinionCenter: [
		number,
		number,
		number
	];
	gearCenter: [
		number,
		number,
		number
	];
}
interface BevelGearPairSpec extends GearPairSpec {
}
interface BevelGearPairOptions {
	pinion: Shape | BevelGearPairSpec;
	gear: Shape | BevelGearPairSpec;
	shaftAngleDeg?: number;
	backlash?: number;
	place?: boolean;
	phaseDeg?: number;
}
interface SideGearSpec extends GearPairSpec {
	side?: "top" | "bottom";
	toothHeight?: number;
}
interface FaceGearSpec extends SideGearSpec {
}
interface SideGearPairOptions {
	side: Shape | SideGearSpec;
	vertical: Shape | GearPairSpec;
	backlash?: number;
	centerDistance?: number;
	meshPlaneZ?: number;
	place?: boolean;
	phaseDeg?: number;
}
interface BevelGearPairResult extends GearMeshPlacement {
	pinion: Shape;
	gear: Shape;
	shaftAngleDeg: number;
	pinionPitchAngleDeg: number;
	gearPitchAngleDeg: number;
	coneDistance: number;
	backlash: number;
	jointRatio: number;
	speedReduction: number;
	diagnostics: GearPairDiagnostic[];
	status: "ok" | "warn" | "error";
}
interface SideGearPairResult {
	side: Shape;
	vertical: Shape;
	centerDistance: number;
	centerDistanceNominal: number;
	backlash: number;
	pressureAngleDeg: number;
	meshPlaneZ: number;
	radialOverlap: number;
	jointRatio: number;
	speedReduction: number;
	diagnostics: GearPairDiagnostic[];
	status: "ok" | "warn" | "error";
}
interface FaceGearPairOptions {
	face: Shape | FaceGearSpec;
	vertical: Shape | GearPairSpec;
	backlash?: number;
	centerDistance?: number;
	meshPlaneZ?: number;
	place?: boolean;
	phaseDeg?: number;
}
interface FaceGearPairResult {
	face: Shape;
	vertical: Shape;
	centerDistance: number;
	centerDistanceNominal: number;
	backlash: number;
	pressureAngleDeg: number;
	meshPlaneZ: number;
	radialOverlap: number;
	jointRatio: number;
	speedReduction: number;
	diagnostics: GearPairDiagnostic[];
	status: "ok" | "warn" | "error";
}
declare function bevelGearPair(options: BevelGearPairOptions): BevelGearPairResult;
declare function sideGearPair(options: SideGearPairOptions): SideGearPairResult;
declare function faceGearPair(options: FaceGearPairOptions): FaceGearPairResult;
/** All library parts, keyed by name */
declare const partLibrary: {
	boltHole: typeof boltHole;
	fastenerHole: typeof fastenerHole;
	counterbore: typeof counterbore;
	tube: typeof tube;
	pipe: typeof pipe;
	explode: typeof explode;
	hexNut: typeof hexNut;
	roundedBox: typeof roundedBox;
	bracket: typeof bracket;
	holePattern: typeof holePattern;
	thread: typeof thread;
	bolt: typeof bolt;
	nut: typeof nut;
	washer: typeof washer;
	fastenerSet: typeof fastenerSet;
	pipeRoute: typeof pipeRoute;
	elbow: typeof elbow;
	tSlotProfile: typeof tSlotProfile;
	tSlotExtrusion: typeof tSlotExtrusion;
	profile2020BSlot6Profile: typeof profile2020BSlot6Profile;
	profile2020BSlot6: typeof profile2020BSlot6;
	spurGear: typeof spurGear;
	bevelGear: typeof bevelGear;
	faceGear: typeof faceGear;
	sideGear: typeof sideGear;
	ringGear: typeof ringGear;
	rackGear: typeof rackGear;
	gearPair: typeof gearPair;
	bevelGearPair: typeof bevelGearPair;
	faceGearPair: typeof faceGearPair;
	sideGearPair: typeof sideGearPair;
};
declare function thread(diameter: number, pitch: number, length: number, options?: {
	depth?: number;
	segments?: number;
}): Shape;
declare function bolt(diameter: number, length: number, options?: {
	pitch?: number;
	headHeight?: number;
	headAcrossFlats?: number;
	threadLength?: number;
	segments?: number;
}): Shape;
declare function nut(diameter: number, options?: {
	pitch?: number;
	height?: number;
	acrossFlats?: number;
	segments?: number;
}): Shape;
type WasherStandard = "din-125-a";
declare function washer(size: MetricSize, options?: {
	standard?: WasherStandard;
	segments?: number;
}): Shape;
interface FastenerSetDimensions {
	size: MetricSize;
	nominalDiameter: number;
	boltLength: number;
	clearanceDia: number;
	tapDia: number;
	nutAcrossFlats: number;
	nutHeight: number;
	washerOuterDia: number;
	washerInnerDia: number;
	washerThickness: number;
}
interface FastenerSetOptions {
	/** Include a washer under the bolt head (default: true). */
	washerUnderHead?: boolean;
	/** Include a washer under the nut (default: true). */
	washerUnderNut?: boolean;
	/** Clearance hole fit (default: 'normal'). */
	fit?: FastenerFit;
	/** Thread segment count (default: 36). */
	segments?: number;
}
interface FastenerSetResult {
	/** Hex bolt: head top at z=0, threaded shaft extends toward −Z by `boltLength`. */
	bolt: Shape;
	/** Hex nut centered at z=0. */
	nut: Shape;
	/** Flat washer centered at z=0. Null when washerUnderHead is false. */
	washerUnderHead: Shape | null;
	/** Flat washer centered at z=0. Null when washerUnderNut is false. */
	washerUnderNut: Shape | null;
	/** Clearance-hole cutter (cylinder) centered at z=0, for subtracting from a through-plate. */
	clearanceHole: Shape;
	/** Tap-drill cutter (cylinder) centered at z=0, for subtracting from a tapped plate. */
	tappedHole: Shape;
	/** Reference dimensions for BOM, placement calculations, and documentation. */
	dims: FastenerSetDimensions;
}
declare function fastenerSet(size: MetricSize, boltLength: number, options?: FastenerSetOptions): FastenerSetResult;
type _ShapeOperand = Shape | TrackedShape;
declare function box(x: number, y: number, z: number, center?: boolean): TrackedShape;
declare function cylinder(height: number, radius: number, radiusTop?: number, segments?: number, center?: boolean): TrackedShape;
declare function sphere(radius: number, segments?: number): Shape;
declare function union(...shapes: (_ShapeOperand | _ShapeOperand[])[]): Shape;
declare function difference(...shapes: (_ShapeOperand | _ShapeOperand[])[]): Shape;
declare function intersection(...shapes: (_ShapeOperand | _ShapeOperand[])[]): Shape;
declare function hull3d(...args: (Shape | TrackedShape | [
	number,
	number,
	number
])[]): Shape;
declare function levelSet(sdf: (p: [
	number,
	number,
	number
]) => number, bounds: {
	min: [
		number,
		number,
		number
	];
	max: [
		number,
		number,
		number
	];
}, edgeLength: number, level?: number): Shape;
declare function importSketch(fileName: string, paramOverrides?: Record<string, number> | SvgImportOptions): Sketch;
declare function importPart(fileName: string, paramOverrides?: Record<string, number>): Shape;
declare function importGroup(fileName: string, paramOverrides?: Record<string, number>): ShapeGroup;
declare function importAssembly(fileName: string, paramOverrides?: Record<string, number>): ImportedAssembly;
declare function importSvgSketch(fileName: string, options?: SvgImportOptions): Sketch;
