/**
 * ForgeCAD — G-code Builder
 *
 * Programmatic toolpath generation for FDM 3D printing.
 * Returns a GCodeBuilder that the runner recognizes as a renderable output type,
 * enabling both viewport visualization and G-code file export.
 */

// ---- Public types ----

export interface PrinterProfile {
  /** Bed width in mm (X axis). Default: 220 */
  bedX?: number;
  /** Bed depth in mm (Y axis). Default: 220 */
  bedY?: number;
  /** Max print height in mm (Z axis). Default: 250 */
  bedZ?: number;
  /** Nozzle diameter in mm. Default: 0.4 */
  nozzle?: number;
  /** Filament diameter in mm. Default: 1.75 */
  filament?: number;
  /** Layer height in mm. Default: 0.2 */
  layerHeight?: number;
  /** Default print speed in mm/min. Default: 1800 (30 mm/s) */
  printSpeed?: number;
  /** Travel (non-extrusion) speed in mm/min. Default: 7200 (120 mm/s) */
  travelSpeed?: number;
  /** Retraction distance in mm. Default: 1.0 */
  retractionDistance?: number;
  /** Retraction speed in mm/min. Default: 2700 (45 mm/s) */
  retractionSpeed?: number;
}

export interface PreheatOptions {
  hotend?: number;
  bed?: number;
}

/** A single segment of toolpath — either extrusion or travel. */
export interface ToolpathSegment {
  /** Start position [x, y, z] */
  from: [number, number, number];
  /** End position [x, y, z] */
  to: [number, number, number];
  /** true = extrusion move, false = travel move */
  extrude: boolean;
  /** Feed rate in mm/min */
  speed: number;
}

/** Serializable toolpath data for rendering and export. */
export interface ToolpathData {
  segments: ToolpathSegment[];
  /** Bounding box of all toolpath points */
  bounds: {
    min: [number, number, number];
    max: [number, number, number];
  };
  /** Raw G-code string for export */
  gcode: string;
  /** Estimated print time in seconds */
  estimatedTimeSeconds: number;
  /** Total extrusion length in mm */
  totalExtrusionMm: number;
  /** Total filament used in mm */
  totalFilamentMm: number;
  /** Nozzle diameter in mm — used by the viewer for bead width */
  beadWidth: number;
  /** Layer height in mm — used by the viewer for bead height */
  beadHeight: number;
}

// ---- Defaults ----

const DEFAULT_PROFILE: Required<PrinterProfile> = {
  bedX: 220,
  bedY: 220,
  bedZ: 250,
  nozzle: 0.4,
  filament: 1.75,
  layerHeight: 0.2,
  printSpeed: 1800,
  travelSpeed: 7200,
  retractionDistance: 1.0,
  retractionSpeed: 2700,
};

// ---- G-code Builder ----

export class GCodeBuilder {
  private profile: Required<PrinterProfile>;
  private pos: [number, number, number] = [0, 0, 0];
  private posInitialized = false; // true after first explicit move
  private e = 0; // cumulative extrusion
  private retracted = false;
  private currentSpeed: number;
  private lines: string[] = [];
  private _segments: ToolpathSegment[] = [];

  // Track bounds
  private _minX = Infinity;
  private _minY = Infinity;
  private _minZ = Infinity;
  private _maxX = -Infinity;
  private _maxY = -Infinity;
  private _maxZ = -Infinity;

  // Filament cross-section area (precomputed)
  private filamentArea: number;

  constructor(profile?: PrinterProfile) {
    this.profile = { ...DEFAULT_PROFILE, ...profile };
    this.currentSpeed = this.profile.printSpeed;
    this.filamentArea = Math.PI * (this.profile.filament / 2) ** 2;
  }

  // ---- Configuration ----

  /** Set print speed in mm/s (converted to mm/min internally). */
  setSpeed(mmPerSec: number): this {
    this.currentSpeed = mmPerSec * 60;
    return this;
  }

  /** Set print speed in mm/min. */
  setSpeedMmMin(mmPerMin: number): this {
    this.currentSpeed = mmPerMin;
    return this;
  }

  /** Set layer height for subsequent extrusion calculations. */
  setLayerHeight(mm: number): this {
    this.profile.layerHeight = mm;
    return this;
  }

  // ---- Preamble / Postamble ----

  /** Add standard start G-code: homing, heating, priming. */
  preheat(opts?: PreheatOptions): this {
    const hotend = opts?.hotend ?? 200;
    const bed = opts?.bed ?? 60;

    this.lines.push('; === ForgeCAD G-code ===');
    this.lines.push('; Generated by ForgeCAD GCodeBuilder');
    this.lines.push('');
    this.lines.push('G21 ; mm units');
    this.lines.push('G90 ; absolute positioning');
    this.lines.push('M82 ; absolute extrusion');
    this.lines.push('');
    this.lines.push(`M140 S${bed} ; set bed temp`);
    this.lines.push(`M104 S${hotend} ; set hotend temp`);
    this.lines.push(`M190 S${bed} ; wait for bed`);
    this.lines.push(`M109 S${hotend} ; wait for hotend`);
    this.lines.push('');
    this.lines.push('G28 ; home all axes');
    this.lines.push('G92 E0 ; reset extruder');
    this.lines.push('');

    this.e = 0;
    this.pos = [0, 0, 0];
    return this;
  }

  /** Add standard end G-code: retract, cool down, present print. */
  cooldown(): this {
    this.retract();
    this.lines.push('');
    this.lines.push('M104 S0 ; hotend off');
    this.lines.push('M140 S0 ; bed off');
    this.lines.push('M107 ; fan off');
    this.lines.push('G91 ; relative positioning');
    this.lines.push('G1 Z10 F600 ; lift nozzle');
    this.lines.push('G90 ; absolute positioning');
    this.lines.push('G1 X0 Y200 F3000 ; present print');
    this.lines.push('M84 ; disable steppers');
    this.lines.push('; === End of ForgeCAD G-code ===');
    return this;
  }

  // ---- Movement ----

  /** Travel (no extrusion) to a point. Auto-retracts. */
  travelTo(x: number, y: number, z: number): this {
    this.retract();
    const from: [number, number, number] = [...this.pos];
    this.lines.push(`G0 X${f(x)} Y${f(y)} Z${f(z)} F${Math.round(this.profile.travelSpeed)}`);
    // Only record a visual segment if position was already initialized
    // (skip the initial home→start travel so it doesn't render as a line from 0,0,0)
    if (this.posInitialized) {
      this._segments.push({ from, to: [x, y, z], extrude: false, speed: this.profile.travelSpeed });
    }
    this.pos = [x, y, z];
    this.posInitialized = true;
    this._updateBounds(x, y, z);
    return this;
  }

  /** Extrude to a point. Auto-unretracts if needed. */
  extrudeTo(x: number, y: number, z: number): this {
    this.unretract();
    const from: [number, number, number] = [...this.pos];
    const dist = Math.sqrt((x - this.pos[0]) ** 2 + (y - this.pos[1]) ** 2 + (z - this.pos[2]) ** 2);

    if (dist < 1e-6) return this; // skip zero-length moves

    // E = (cross-section of extruded bead) * distance / filament cross-section
    const beadArea = this.profile.layerHeight * this.profile.nozzle;
    const eIncrement = (beadArea * dist) / this.filamentArea;
    this.e += eIncrement;

    this.lines.push(`G1 X${f(x)} Y${f(y)} Z${f(z)} E${f(this.e)} F${Math.round(this.currentSpeed)}`);
    if (this.posInitialized) {
      this._segments.push({ from, to: [x, y, z], extrude: true, speed: this.currentSpeed });
    }
    this.pos = [x, y, z];
    this.posInitialized = true;
    this._updateBounds(x, y, z);
    return this;
  }

  /** Extrude a relative displacement. */
  extrudeBy(dx: number, dy: number, dz: number): this {
    return this.extrudeTo(this.pos[0] + dx, this.pos[1] + dy, this.pos[2] + dz);
  }

  /** Travel a relative displacement. */
  travelBy(dx: number, dy: number, dz: number): this {
    return this.travelTo(this.pos[0] + dx, this.pos[1] + dy, this.pos[2] + dz);
  }

  // ---- Fan ----

  /** Set fan speed (0-255 or 0.0-1.0). */
  setFan(speed: number): this {
    const s = speed <= 1 ? Math.round(speed * 255) : Math.round(speed);
    this.lines.push(`M106 S${Math.min(255, Math.max(0, s))}`);
    return this;
  }

  fanOff(): this {
    this.lines.push('M107');
    return this;
  }

  // ---- Raw G-code ----

  /** Insert a comment into the G-code. */
  comment(text: string): this {
    this.lines.push(`; ${text}`);
    return this;
  }

  /** Insert raw G-code line(s). */
  raw(line: string): this {
    this.lines.push(line);
    return this;
  }

  // ---- Retraction ----

  private retract(): void {
    if (this.retracted) return;
    this.e -= this.profile.retractionDistance;
    this.lines.push(`G1 E${f(this.e)} F${Math.round(this.profile.retractionSpeed)}`);
    this.retracted = true;
  }

  private unretract(): void {
    if (!this.retracted) return;
    this.e += this.profile.retractionDistance;
    this.lines.push(`G1 E${f(this.e)} F${Math.round(this.profile.retractionSpeed)}`);
    this.retracted = false;
  }

  // ---- Bounds tracking ----

  private _updateBounds(x: number, y: number, z: number): void {
    if (x < this._minX) this._minX = x;
    if (y < this._minY) this._minY = y;
    if (z < this._minZ) this._minZ = z;
    if (x > this._maxX) this._maxX = x;
    if (y > this._maxY) this._maxY = y;
    if (z > this._maxZ) this._maxZ = z;
  }

  // ---- Output ----

  /** Get the current position. */
  getPosition(): [number, number, number] {
    return [...this.pos];
  }

  /** Build the complete toolpath data (for serialization and rendering). */
  build(): ToolpathData {
    const gcode = this.lines.join('\n') + '\n';

    // Estimate print time from segments
    let totalTimeSeconds = 0;
    let totalExtrusionMm = 0;
    for (const seg of this._segments) {
      const dist = Math.sqrt((seg.to[0] - seg.from[0]) ** 2 + (seg.to[1] - seg.from[1]) ** 2 + (seg.to[2] - seg.from[2]) ** 2);
      totalTimeSeconds += dist / (seg.speed / 60); // speed is mm/min, want seconds
      if (seg.extrude) totalExtrusionMm += dist;
    }

    const hasPoints = this._minX !== Infinity;

    return {
      segments: this._segments,
      bounds: {
        min: hasPoints ? [this._minX, this._minY, this._minZ] : [0, 0, 0],
        max: hasPoints ? [this._maxX, this._maxY, this._maxZ] : [0, 0, 0],
      },
      gcode,
      estimatedTimeSeconds: totalTimeSeconds,
      totalExtrusionMm,
      totalFilamentMm: this.e,
      beadWidth: this.profile.nozzle,
      beadHeight: this.profile.layerHeight,
    };
  }

  /** Generate the G-code string. */
  toGCode(): string {
    return this.lines.join('\n') + '\n';
  }
}

// ---- Helpers ----

/** Format a number for G-code (5 decimal places, strip trailing zeros). */
function f(n: number): string {
  return n.toFixed(5).replace(/\.?0+$/, '');
}

// ---- Factory function for user scripts ----

/**
 * Create a new G-code builder with an optional printer profile.
 *
 * Usage in .forge.js scripts:
 * ```js
 * const g = gcode({ nozzle: 0.4, layerHeight: 0.2 });
 * g.preheat({ hotend: 200, bed: 60 });
 * // ... build toolpath ...
 * g.cooldown();
 * export default g;
 * ```
 */
export function gcode(profile?: PrinterProfile): GCodeBuilder {
  return new GCodeBuilder(profile);
}
