export { Shape, box, cylinder, sphere, union, difference, intersection, initKernel } from './kernel';
export { intersectWithPlane, projectToPlane } from './section';
export type { PlaneSpec } from './section';
export * from './sketch';
export { param } from './params';
export { runScript } from './runner';
export { partLibrary } from './library';
export { shapeToGeometry } from './meshToGeometry';
export { buildScene } from './sceneBuilder';
export type { ParamDef } from './params';
export type { RunResult, SceneObject } from './runner';
export type { ForgeGeometry } from './meshToGeometry';
